--
-- DATABASE @ssdb @crvl
--
--\cd @ddldir
--!!dir *.sql
--
--\encoding
--\encoding LATIN1
--\encoding
--\set AUTOCOMMIT off
-- --------------------------------------------------------------------------
-- BEGIN TRANSACTION
-- --------------------------------------------------------------------------
-- file:MHZDB201_SS_100
-- --------------------------------------------------------------------------
-- :r MHZDB201_SS_100.sql
-- --------------------------------------------------------------------------
-- file:MHZDB201_SS_200
-- --------------------------------------------------------------------------
-- :r MHZDB201_SS_200.sql
-- --------------------------------------------------------------------------
-- file:MHZDB201_SS_300
-- --------------------------------------------------------------------------
-- :r MHZDB201_SS_300.sql
-- --------------------------------------------------------------------------
-- file:MHZDB201_SS_400
-- --------------------------------------------------------------------------
-- :r MHZDB201_SS_400.sql
-- --------------------------------------------------------------------------
-- file:MHZDB201_SS_500
-- --------------------------------------------------------------------------
-- :r MHZDB201_SS_500.sql
-- --------------------------------------------------------------------------
-- file:MHZDB201_SS_600
-- --------------------------------------------------------------------------
-- :r MHZDB201_SS_600.sql
-- --------------------------------------------------------------------------
update dual set version_dual = @crvl
go
-- --------------------------------------------------------------------------
-- COMMIT TRANSACTION
-- --------------------------------------------------------------------------
select version_dual from dual
go
-- ----------------------------------------------------------------------------------------------------------------------------------
-- ordena las opciones del menu
-- ----------------------------------------------------------------------------------------------------------------------------------
select opcion_menu_rebuild()
go
-- ----------------------------------------------------------------------------------------------------------------------------------
-- esconde las opciones del menu correspondientes al SDK
-- ----------------------------------------------------------------------------------------------------------------------------------
update opcion_menu set es_opcion_menu_inactiva=1 where codigo_opcion_menu like'N9%'
go
-- ----------------------------------------------------------------------------------------------------------------------------------
-- muestra las opciones del menu correspondientes al SDK
-- ----------------------------------------------------------------------------------------------------------------------------------
update opcion_menu set es_opcion_menu_inactiva=0 where codigo_opcion_menu like'N9%' and codigo_opcion_menu not like'N92%'
go
select clave_opcion_menu,codigo_opcion_menu,nombre_opcion_menu,es_opcion_menu_inactiva 
from opcion_menu where codigo_opcion_menu like'N9%' order by 1,2
go
SELECT		[xtype], COUNT(*) AS [count], MIN([name]) AS [min], MAX([name]) AS [max]
FROM		[sysobjects]
WHERE		([xtype] IN ('U','V','P','FN') AND ([xtype]<>'V' OR [category]=0) AND [name] NOT LIKE 'dt%')
OR		([parent_obj] IN (SELECT [id] FROM [sysobjects] WHERE [xtype]='U' AND [name] NOT LIKE 'dt%'))
GROUP BY	[xtype]
UNION
SELECT		'IX' AS [xtype], COUNT(*) AS [count], MIN([name]) AS [min], MAX([name]) AS [max]
FROM 		[sysindexes]
WHERE		[name] NOT LIKE '%SYS%'
AND		[name] NOT IN (SELECT [name] FROM [sysobjects])
AND		[id] IN (SELECT [id] FROM [sysobjects] WHERE [xtype]='U' AND [name] NOT LIKE 'dt%')
ORDER BY 	[xtype]
GO
QUIT
