--Esta tabla registra la importación de fichas_hogar
--Antes de ejecutar el procedimiento se crea una tabla de rastro que permitira 
--auditar la importación
create  table log_imp_hog(
            id_log_imp_hog serial,
            P20D character varying(4),
            P20M character varying(4),
            P20A character varying(4),
            P17  character varying(30),
            P18 character varying (30),
            VAR00001 character varying(30),
            P19 character varying(30),
            observaciones character varying,
            UTM character varying(30),
            GPS character varying(30),
            ORDEN character varying(30),
            COORDX character varying(30),
            P01A character varying(30),
            P01B character varying(30),
            P01C character varying (30),
            P01D character varying (30),
            P02 character varying(30),
            P03 character varying(30),
            P04 character varying(30),
            P05 character varying(30),
            P06 character varying(30),
            P08 character varying(30),
            P07 character varying(30),
            P09 character varying,
            P14 character varying(4),
            P15 character varying(4),
            P16 character varying(4),
            P24 character varying(4),
            P25 character varying(4),
            P26 character varying(4),
            P27 character varying(4),
            P27E character varying,
            P28A character varying(4),
            P28B character varying(4),
            P29 character varying(4),
            P30 character varying(4),
            P31 character varying(4),
            P32 character varying(4),
            P33 character varying(4),
            P34 character varying(4),
            P35 character varying(4),
            P36 character varying(4),
            P37 character varying(4),
            Nro_celular character varying(30),
            P38 character varying(4),
            Nro_linea_baja character varying(30),
            P391 character varying(4),
            P392 character varying(4),
            P393 character varying(4),
            P394 character varying(4),
            P395 character varying(4),
            P396 character varying(4),
            P397 character varying(4),
            P42N character varying(100),
            P42CI character varying(100),
            letra_ci character varying(4),
            P43 character varying(30),
            VAR00002 character varying(100),
            VAR00003 character varying(100),
            VAR00004 character varying(100),
            P104 character varying(4),
            importado integer,
            observacion character varying,
            fecha_transaccion timestamp with time zone,
            nombre_archivo character varying,
            codigo_archivo character varying,
            constraint pk_log_imp_hog primary key (id_log_imp_hog)
);
