--Esta tabla registra la importación de fichas_persona
--Antes de ejecutar el procedimiento se crea una tabla de rastro que permitira 
--auditar la importación
create  table log_imp_per(
            id_log_imp_per serial,
            P01A character varying(30),
            P01B character varying(30),
            P01C character varying (30),
            P01D character varying (30),
            P02 character varying(30),
            P03 character varying(30),
            P104 character varying(4),
            P43 character varying(4),
            P45A character varying(50),
            P45B character varying(50),
            P44A character varying(50),
            P44B character varying(50),
            VAR00001 character varying(30),
            VAR00002 character varying(30),
            P46 character varying(4),
            P47 character varying(4),
            VAR00030 character varying(4),
            P48 character varying(30),
            P49 character varying(4),
            P50A character varying(4),
            P50B character varying(4),
            P50C character varying(4),
            P51 character varying(30),
            VAR00003 character varying(4),
            VAR00004 character varying(30),
            P52D character varying(4),
            P52M character varying(4),
            P52A character varying(4),
            P53A character varying(100),
            P53B character varying(100),
            P53C character varying(100),
            P53Z character varying(4),
            P54 character varying(4),
            P54E character varying,
            P56 character varying(4),
            P58 character varying(4),
            P58E character varying,
            P59 character varying(4),
            P60 character varying(4),
            P61 character varying(4),
            P62 character varying(4),
            P63 character varying(4),
            P64 character varying(4),
            P65 character varying(4),
            P65E character varying,
            P66 character varying(4),
            P66E character varying,
            P67 character varying(4),
            P68 character varying(4),
            P68E character varying,
            P73 character varying(4),
            P74 character varying(4),
            VAR00006 character varying(100),
            VAR00007 character varying(4),
            VAR00008 character varying(4),
            VAR00009 character varying(4),
            VAR00010 character varying(4),
            VAR00011 character varying(4),
            VAR00031 character varying(4),
            VAR00012 character varying(4),
            VAR00013 character varying(4),
            P86 character varying(4),
            P87 character varying(4),
            P87E character varying,
            P88 character varying(4),
            P88E character varying,
            P91 character varying(4),
            VAR00017 character varying(30),
            VAR00018 character varying(30),
            VAR00019 character varying(30),
            VAR00020 character varying(30),
            VAR00021 character varying(30),
            VAR00022 character varying(30),
            VAR00023 character varying(30),
            VAR00024 character varying(30),
            VAR00025 character varying(30),
            VAR00026 character varying(30),
            VAR00027 character varying(30),
            VAR00028 character varying(30),
            P92 character varying(30),
            ICV character varying(30),
            ficha_activa character varying(4),
            importado integer,
            observacion character varying,
            fecha_transaccion timestamp with time zone,
            nombre_archivo character varying,
            codigo_archivo character varying,
            constraint pk_log_imp_per primary key (id_log_imp_per)
            );
