COMMENT ON TABLE  clase_recurso_par IS '';
COMMENT ON COLUMN clase_recurso_par.es_parametro_omisible IS 'Solo lectura al crear';
COMMENT ON COLUMN clase_recurso_par.es_parametro_inmutable IS 'Solo lectura al modificar';
COMMENT ON COLUMN clase_recurso_par.es_parametro_submit IS 'Auto-Submit on Change';
COMMENT ON TABLE  ficha_hogar IS '';
COMMENT ON COLUMN ficha_hogar.observaciones IS 'Observaciones de campo';
COMMENT ON COLUMN ficha_hogar.huso_utm IS 'Número de Zona ó Huso (1-60) de la ubicación de la vivienda (según GPS)';
COMMENT ON COLUMN ficha_hogar.franja_utm IS 'Banda ó Franja (C-X, sin I ni O) de la ubicación de la vivienda (según GPS)';
COMMENT ON COLUMN ficha_hogar.distancia_este_utm IS 'Coordenada X: distancia horizontal al Este (Easting) de la ubicación de la vivienda (según GPS)';
COMMENT ON COLUMN ficha_hogar.distancia_norte_utm IS 'Coordenada Y: distancia vertical al Norte (Northing) de la ubicación de la vivienda (según GPS)';
COMMENT ON COLUMN ficha_hogar.numero_tipo_area IS 'Tipo de área (urbana o rural)';
COMMENT ON COLUMN ficha_hogar.numero_tipo_mat_paredes IS 'Material predominante en las paredes exteriores';
COMMENT ON COLUMN ficha_hogar.numero_tipo_mat_piso IS 'Material predominante en el piso';
COMMENT ON COLUMN ficha_hogar.numero_tipo_mat_techo IS 'Material predominante en el techo';
COMMENT ON COLUMN ficha_hogar.numero_tipo_ocupacion_viv IS 'Condición de ocupación de la vivienda';
COMMENT ON COLUMN ficha_hogar.otro_tipo_ocupacion_viv IS 'Condición de ocupación de la vivienda (especificar si la respuesta anterior es 6 "Otros")';
COMMENT ON COLUMN ficha_hogar.cantidad_piezas IS 'Número de piezas, sin incluir baño, cocina, cuartos o piezas destinadas exclusivamente al comercio o industria';
COMMENT ON COLUMN ficha_hogar.cantidad_dormitorios IS 'Número de dormitorios';
COMMENT ON COLUMN ficha_hogar.numero_siono_pieza_cocina IS 'Tiene pieza para cocinar';
COMMENT ON COLUMN ficha_hogar.numero_tipo_combustible IS 'Combustible que se utiliza en forma habitual para cocinar';
COMMENT ON COLUMN ficha_hogar.numero_tipo_pieza_bano IS 'Tipo de pieza para bañarse';
COMMENT ON COLUMN ficha_hogar.numero_tipo_servicio_san IS 'Tipo de desagüe que tiene el baño';
COMMENT ON COLUMN ficha_hogar.numero_tipo_servicio_agua IS 'Procedencia del agua que se utiliza en l a vivienda';
COMMENT ON COLUMN ficha_hogar.numero_tipo_aba_agua IS 'Lugar de abastecimiento del agua que se utiliza en l a vivienda';
COMMENT ON COLUMN ficha_hogar.numero_siono_corriente_elec IS 'Dispone de luz eléctrica';
COMMENT ON COLUMN ficha_hogar.numero_tipo_desecho_bas IS 'Forma de desechar la basura';
COMMENT ON COLUMN ficha_hogar.numero_siono_telefono_celular IS 'Tiene teléfono celular';
COMMENT ON COLUMN ficha_hogar.numero_telefono_celular IS 'Número de teléfono celular';
COMMENT ON COLUMN ficha_hogar.numero_siono_tlf_linea_baja IS 'Tiene teléfono de linea baja';
COMMENT ON COLUMN ficha_hogar.numero_telefono_linea_baja IS 'Número de teléfono de linea baja';
COMMENT ON COLUMN ficha_hogar.numero_siono_disp_heladera IS 'Dispone de heladera en el hogar';
COMMENT ON COLUMN ficha_hogar.numero_siono_disp_lavarropas IS 'Dispone de lavarropas en el hogar';
COMMENT ON COLUMN ficha_hogar.numero_siono_disp_termo IS 'Dispone de termocalefón en el hogar';
COMMENT ON COLUMN ficha_hogar.numero_siono_disp_aire_acon IS 'Dispone de aire acondicionado en el hogar';
COMMENT ON COLUMN ficha_hogar.numero_siono_disp_automovil IS 'Dispone de automóvil ó camioneta en el hogar';
COMMENT ON COLUMN ficha_hogar.numero_siono_disp_camion IS 'Dispone de camión en el hogar';
COMMENT ON COLUMN ficha_hogar.numero_siono_disp_motocicleta IS 'Dispone de motocicleta en el hogar';
COMMENT ON COLUMN ficha_hogar.nombre_jefe_hogar IS 'Nombre del jefe de hogar';
COMMENT ON COLUMN ficha_hogar.numero_cedula_jefe_hogar IS 'Número de cédula del jefe de hogar';
COMMENT ON COLUMN ficha_hogar.letra_cedula_jefe_hogar IS 'Letra de la cédula del jefe de hogar';
COMMENT ON COLUMN ficha_hogar.numero_orden_iden_jefe_hogar IS 'Número de orden de identificación del jefe de hogar';
COMMENT ON COLUMN ficha_hogar.nombre_respondente IS 'Nombre del respondente';
COMMENT ON COLUMN ficha_hogar.numero_cedula_respondente IS 'Número de cédula del respondente';
COMMENT ON COLUMN ficha_hogar.letra_cedula_respondente IS 'Letra de la cédula del respondente';
COMMENT ON COLUMN ficha_hogar.numero_orden_iden_respondente IS 'Número de orden de identificación del respondente';
COMMENT ON TABLE  ficha_persona IS '';
COMMENT ON COLUMN ficha_persona.numero_orden_identificacion IS 'Número de orden de identificación de la persona';
COMMENT ON COLUMN ficha_persona.numero_tipo_persona_hogar IS 'Parentesco familiar con el/la jefe/a del hogar';
COMMENT ON COLUMN ficha_persona.numero_siono_miembro_hogar IS 'Es miembro del hogar';
COMMENT ON COLUMN ficha_persona.numero_orden_iden_conyuge IS 'Número de orden de identificación del conyuge';
COMMENT ON COLUMN ficha_persona.numero_orden_iden_padre IS 'Número de orden de identificación del padre';
COMMENT ON COLUMN ficha_persona.numero_orden_iden_madre IS 'Número de orden de identificación de la madre';
COMMENT ON COLUMN ficha_persona.numero_tipo_excepcion_ced IS 'Razón por la que no se dispone del número de cédula de la persona';
COMMENT ON COLUMN ficha_persona.id_departamento_nacimiento IS 'Departamento donde vivía la madre cuando nació';
COMMENT ON COLUMN ficha_persona.id_distrito_nacimiento IS 'Distrito donde vivía la madre cuando nació';
COMMENT ON COLUMN ficha_persona.numero_tipo_area_lugar_nac IS 'Tipo de área (urbana o rural) donde vivía la madre cuando nació';
COMMENT ON COLUMN ficha_persona.numero_idioma_hogar IS 'Idioma que habla en la casa la mayor parte del tiempo';
COMMENT ON COLUMN ficha_persona.otro_idioma_hogar IS 'Idioma que habla en la casa la mayor parte del tiempo (especificar si la respuesta anterior es 4 "Otro idioma")';
COMMENT ON COLUMN ficha_persona.numero_siono_asistencia_esc IS 'Asiste o asistió a una escuela, colegio o institucion de enseñanza regular';
COMMENT ON COLUMN ficha_persona.numero_motivo_ina_esc IS 'Motivo por el que no asiste o dejó de asistir a la escuela, colegio o institucion de enseñanza regular';
COMMENT ON COLUMN ficha_persona.otro_motivo_ina_esc IS 'Motivo por el que no asiste o dejó de asistir a la escuela, colegio o institucion de enseñanza regular (especificar si la respuesta anterior es 25 "Otros")';
COMMENT ON COLUMN ficha_persona.numero_siono_matriculacion_esc IS 'Esta matriculado actualmente en una institución educativa';
COMMENT ON COLUMN ficha_persona.ultimo_curso_aprobado IS 'Ultimo grado/ciclo o curso que aprobó';
COMMENT ON COLUMN ficha_persona.numero_nivel_edu_ult_cur_aprob IS 'Nivel al que corresponde el último grado/ciclo o curso que aprobó';
COMMENT ON COLUMN ficha_persona.numero_siono_curso_no_formal IS 'Realizó algún curso no formal para poder trabajar, ejercer algún oficio o mejorar su nivel cultural';
COMMENT ON COLUMN ficha_persona.numero_tipo_seguro_medico IS 'Tiene seguro médico vigente en el país';
COMMENT ON COLUMN ficha_persona.numero_estado_salud IS 'Durante los últimos 90 dias, se sintió o estuvo enfermo y/o accidentado';
COMMENT ON COLUMN ficha_persona.numero_clase_enf_acc IS 'Enfermedad y/o accidente que tuvo durante los últimos 90 dias';
COMMENT ON COLUMN ficha_persona.otra_clase_enf_acc IS 'Enfermedad y/o accidente que tuvo durante los últimos 90 dias (especificar si la respuesta anterior es 44 "Otros")';
COMMENT ON COLUMN ficha_persona.numero_clase_enf_cronica IS 'Enfermedad crónica que tiene';
COMMENT ON COLUMN ficha_persona.otra_clase_enf_cronica IS 'Enfermedad crónica que tiene (especificar si la respuesta anterior es 42 "Otros")';
COMMENT ON COLUMN ficha_persona.numero_siono_atencion_medica IS 'Recibió atención médica por la enfermedad y/o accidente que tuvo o tiene';
COMMENT ON COLUMN ficha_persona.numero_motivo_no_atencion IS 'Motivo por el que no recibió atención médica';
COMMENT ON COLUMN ficha_persona.otro_motivo_no_atencion IS 'Motivo por el que no recibió atención médica (especificar si la respuesta anterior es 9 "Otros")';
COMMENT ON COLUMN ficha_persona.numero_siono_carnet_vacunacion IS 'Tiene carnet de vacunación';
COMMENT ON COLUMN ficha_persona.numero_clase_impedimento IS 'Tiene impedimento físico o mental de forma permanente';
COMMENT ON COLUMN ficha_persona.otra_clase_impedimento IS 'Tiene impedimento físico o mental de forma permanente (especificar si la respuesta anterior es 13 "Otros")';
COMMENT ON COLUMN ficha_persona.numero_causa_impedimento IS 'Causa del impedimento';
COMMENT ON COLUMN ficha_persona.otra_causa_impedimento IS 'Causa del impedimento (especificar si la respuesta anterior es 5 "Otros")';
COMMENT ON COLUMN ficha_persona.numero_siono_dif_para_caminar IS 'Tiene dificultad para cruzar una pieza/habitación caminando';
COMMENT ON COLUMN ficha_persona.numero_siono_dif_para_vestirse IS 'Tiene dificultad para vestirse, incluyendo ponerse los zapatos y las medias';
COMMENT ON COLUMN ficha_persona.numero_siono_dif_para_banarse IS 'Tiene dificultad para bañarse, incluyendo entrar y salid de la bañadera';
COMMENT ON COLUMN ficha_persona.numero_siono_dif_para_comer IS 'Tiene dificultad para comer, incluyendo cortar la comida, llenar los vasos, etc.';
COMMENT ON COLUMN ficha_persona.numero_siono_dif_para_la_cama IS 'Tiene dificultad para acostarse o pararse de la cama';
COMMENT ON COLUMN ficha_persona.numero_siono_dif_para_el_bano IS 'Tiene dificultad para usar el servicio sanitario, incluyendo sentarse o levantarse del excusado o inodoro';
COMMENT ON COLUMN ficha_persona.numero_siono_trabajo IS 'Durante los últimos 30 dias trabajó, realizó alguna changa, o hizo algún producto dentro o fuera de su casa para vender, o prestó algún servicio, o ayudó a alguien en su trabajo, negocio o chacra';
COMMENT ON COLUMN ficha_persona.numero_motivo_no_trabajo IS 'Motivo principal por el que no trabajó durante los últimos 30 dias';
COMMENT ON COLUMN ficha_persona.otro_motivo_no_trabajo IS 'Motivo principal por el que no trabajó durante los últimos 30 dias (especificar si la respuesta anterior es 9 "Otros")';
COMMENT ON COLUMN ficha_persona.descripcion_ocupacion_prin IS 'Ocupación principal en el trabajo que realiza o realizaba';
COMMENT ON COLUMN ficha_persona.descripcion_dedicacion_prin IS 'Producto o servicio principal que se produce o se presta en el lugar donde trabaja o trabajaba';
COMMENT ON COLUMN ficha_persona.numero_tipo_relacion_lab IS 'Relación laboral que mentiene o mantenía';
COMMENT ON COLUMN ficha_persona.monto_ingreso_ocupacion_prin IS 'Monto del ingreso mensual que habitualmente recibe en su ocupación principal';
COMMENT ON COLUMN ficha_persona.monto_ingreso_ocupacion_secun IS 'Monto del ingreso mensual que habitualmente recibe en su ocupación secundaria';
COMMENT ON COLUMN ficha_persona.monto_ingreso_otras_ocup IS 'Monto del ingreso mensual que habitualmente recibe en todas las otras ocupaciones';
COMMENT ON COLUMN ficha_persona.monto_ingreso_alquileres IS 'Monto del ingreso mensual que habitualmente recibe por alquileres o rentas (neto)';
COMMENT ON COLUMN ficha_persona.monto_ingreso_intereses IS 'Monto del ingreso mensual que habitualmente recibe por intereses, dividendos o utilidades';
COMMENT ON COLUMN ficha_persona.monto_ingreso_ayuda_fam_pais IS 'Monto del ingreso mensual que habitualmente recibe por ayuda familiar del país';
COMMENT ON COLUMN ficha_persona.monto_ingreso_ayuda_fam_exter IS 'Monto del ingreso mensual que habitualmente recibe por ayuda familiar del exterior';
COMMENT ON COLUMN ficha_persona.monto_ingreso_jubilacion IS 'Monto del ingreso mensual que habitualmente recibe por jubilación o pensión';
COMMENT ON COLUMN ficha_persona.monto_ingreso_pensiones IS 'Monto del ingreso mensual que habitualmente recibe por pensiones o prestaciones por divorcios o cuidados de hijos';
COMMENT ON COLUMN ficha_persona.monto_ingreso_tekopora IS 'Monto del ingreso mensual que habitualmente recibe por Tekopora';
COMMENT ON COLUMN ficha_persona.monto_ingreso_programas IS 'Monto del ingreso mensual que habitualmente recibe por otros programas';
COMMENT ON COLUMN ficha_persona.monto_ingreso_adicional IS 'Monto del ingreso mensual que habitualmente recibe por otras fuentes';
COMMENT ON COLUMN ficha_persona.total_ingreso_mensual IS 'Monto total del ingreso mensual que habitualmente recibe por cualquier fuente (suma de todos los montos anteriores)';
COMMENT ON TABLE  nivel_educativo IS '';
COMMENT ON COLUMN nivel_educativo.primer_curso IS 'Número del primer curso del nivel';
COMMENT ON COLUMN nivel_educativo.ultimo_curso IS 'Número del último curso del nivel';
COMMENT ON TABLE  persona IS '';
COMMENT ON COLUMN persona.otra_causa_den_pension IS 'Especificar si la respuesta anterior es 99 "Otra causa"';
COMMENT ON COLUMN persona.otra_causa_rev_pension IS 'Especificar si la respuesta anterior es 99 "Otra causa"';
COMMENT ON COLUMN persona.otra_causa_den_reco_pen IS 'Especificar si la respuesta anterior es 99 "Otra causa"';
COMMENT ON TABLE  potencial_ben IS '';
COMMENT ON COLUMN potencial_ben.es_persona_con_empleo IS 'tiene empleo';
COMMENT ON COLUMN potencial_ben.es_persona_con_jubilacion IS 'tiene jubilación';
COMMENT ON COLUMN potencial_ben.es_persona_con_pension IS 'tiene pensión';
COMMENT ON COLUMN potencial_ben.es_persona_con_subsidio IS 'tiene algún subsidio del Estado';
COMMENT ON COLUMN potencial_ben.es_persona_con_deuda IS 'tiene deudas con el Estado';
COMMENT ON COLUMN potencial_ben.es_persona_con_pena_judicial IS 'tiene pena judicial pendiente';
COMMENT ON COLUMN potencial_ben.es_persona_con_cer_vida IS 'presentó Certificado de Vida y Residencia';
COMMENT ON COLUMN potencial_ben.es_persona_con_carta_renuncia IS 'está dispuesto a firmar la Carta de Renuncia a otras pensiones y/o subsidios';
COMMENT ON COLUMN potencial_ben.otra_causa_inv_censo IS 'Especificar si la respuesta anterior es 99 "Otra causa"';
COMMENT ON COLUMN potencial_ben.otra_causa_den_recl_cen IS 'Especificar si la respuesta anterior es 99 "Otra causa"';
