\echo
\echo DATABASE :pgdb :crvl
\echo
\cd W:/mhzap201/source/development/resources/scripts/sql/data
\echo
\encoding
\encoding LATIN1
\encoding
\set AUTOCOMMIT off
\echo ----------------------------------------------------------------------------------------------------------------------------------
BEGIN TRANSACTION;
\echo ----------------------------------------------------------------------------------------------------------------------------------
update recaudo set es_recaudo_eliminable=1;
delete from recaudo;
delete from garantia_credito;
delete from garantia_linea_credito;
delete from limite_linea_credito;
delete from credito;
delete from linea_credito;
delete from deposito_plazo;
delete from deposito_vista;
delete from tarjeta_credito;
delete from tramite_divisa;
delete from credito_externo;
delete from deposito_externo;
delete from tarjeta_credito_externa;
delete from tramite_divisa_externo;
delete from egreso_persona;
delete from empleo_persona;
delete from patrimonio_persona;
delete from persona_accionista;
delete from persona_apoderado;
delete from persona_cliente;
delete from persona_competidor;
delete from persona_director;
delete from persona_ejecutivo;
delete from persona_proveedor;
delete from producto_persona;
delete from producto_servicio_persona;
delete from referencia_bancaria;
delete from referencia_comercial;
delete from referencia_personal;
delete from relacion_riesgo;
delete from rubro_lustro_situacion_financiera;
delete from rubro_situacion_financiera;
delete from situacion_financiera;
update persona set id_grupo_economico=null;
delete from grupo_economico;
\echo ----------------------------------------------------------------------------------------------------------------------------------
\i persona.sql
\i usuario.sql
\i agencia.sql
\i grupo_economico.sql
\i credito_externo.sql
\i deposito_externo.sql
\i tarjeta_credito_externa.sql
\i tramite_divisa_externo.sql
\i egreso_persona.sql
\i empleo_persona.sql
\i patrimonio_persona.sql
\i persona_accionista.sql
\i persona_apoderado.sql
\i persona_cliente.sql
\i persona_competidor.sql
\i persona_director.sql
\i persona_ejecutivo.sql
\i persona_proveedor.sql
\i producto_persona.sql
\i producto_servicio_persona.sql
\i referencia_bancaria.sql
\i referencia_comercial.sql
\i referencia_personal.sql
\i relacion_riesgo.sql
\i situacion_financiera.sql
\i tramite_divisa.sql
\i tarjeta_credito.sql
\i deposito_plazo.sql
\i deposito_vista.sql
\i linea_credito.sql
\i credito.sql
\i limite_linea_credito.sql
\i garantia_linea_credito.sql
\i garantia_credito.sql
\echo ----------------------------------------------------------------------------------------------------------------------------------
update recaudo set numero_condicion=3 where numero_condicion=1;
\echo ----------------------------------------------------------------------------------------------------------------------------------
select count(*) from grupo_economico;
select count(*) from persona;
select count(*) from usuario;
select count(*) from agencia;
select count(*) from credito_externo;
select count(*) from deposito_externo;
select count(*) from tarjeta_credito_externa;
select count(*) from tramite_divisa_externo;
select count(*) from egreso_persona;
select count(*) from empleo_persona;
select count(*) from patrimonio_persona;
select count(*) from persona_accionista;
select count(*) from persona_apoderado;
select count(*) from persona_cliente;
select count(*) from persona_competidor;
select count(*) from persona_director;
select count(*) from persona_ejecutivo;
select count(*) from persona_proveedor;
select count(*) from producto_persona;
select count(*) from producto_servicio_persona;
select count(*) from referencia_bancaria;
select count(*) from referencia_comercial;
select count(*) from referencia_personal;
select count(*) from relacion_riesgo;
select count(*) from situacion_financiera;
select count(*) from rubro_situacion_financiera;
select count(*) from rubro_lustro_situacion_financiera;
select count(*) from tramite_divisa_externo;
select count(*) from tarjeta_credito;
select count(*) from deposito_plazo;
select count(*) from deposito_vista;
select count(*) from linea_credito;
select count(*) from credito;
select count(*) from limite_linea_credito;
select count(*) from garantia_linea_credito;
select count(*) from garantia_credito;
\echo ----------------------------------------------------------------------------------------------------------------------------------
COMMIT TRANSACTION;
\echo ----------------------------------------------------------------------------------------------------------------------------------
\q
