\echo
\echo DATABASE :pgdb :crvl
\echo
\echo
\encoding
\encoding LATIN1
\encoding
\set AUTOCOMMIT on
\echo ----------------------------------------------------------------------------------------------------------------------------------
\echo ordena las opciones del menu
\echo ----------------------------------------------------------------------------------------------------------------------------------
select opcion_menu_rebuild();
\echo ----------------------------------------------------------------------------------------------------------------------------------
\echo esconde las opciones del menu correspondientes al SDK
\echo ----------------------------------------------------------------------------------------------------------------------------------
update opcion_menu set es_opcion_menu_inactiva=1 where codigo_opcion_menu like'N9%';
\echo ----------------------------------------------------------------------------------------------------------------------------------
\echo muestra las opciones del menu correspondientes al SDK
\echo ----------------------------------------------------------------------------------------------------------------------------------
-- update opcion_menu set es_opcion_menu_inactiva=0 where codigo_opcion_menu like'N9%' and codigo_opcion_menu not like'N92%';
select clave_opcion_menu,codigo_opcion_menu,nombre_opcion_menu,es_opcion_menu_inactiva 
from opcion_menu where codigo_opcion_menu like'N9%' order by 1,2;
