<?xml version="1.0" encoding="UTF-8"?>
<!--
   Copyright (C) 2008, EGT Consultores, C.A.
   Este programa es software libre; usted puede redistribuirlo y/o modificarlo bajo los terminos
   de la licencia "GNU General Public License" publicada por la Fundacion "Free Software Foundation".
   Este programa se distribuye con la esperanza de que pueda ser util, pero SIN NINGUNA GARANTIA;
   vea la licencia "GNU General Public License" para obtener mas informacion.
-->
<jsp:root version="2.1"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:jsp="http://java.sun.com/JSP/Page" 
    xmlns:webuijsf="http://www.sun.com/webui/webuijsf">
    <jsp:directive.page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"/>
    <f:view>
        <webuijsf:page id="page1">
            <webuijsf:html id="html1">
                <webuijsf:head id="head1" title="#{ApplicationBean1.nombreAplicacion}">
                    <webuijsf:link id="link1" url="/resources/stylesheet.css"/>
                    <webuijsf:script id="script1" url="/resources/javascript1.js"/>
                </webuijsf:head>
                <webuijsf:body 
                    focus="#{GrupoAplicacion2.gestor.focus}"
                    id="body1"
                    onClick="#{ApplicationBean1.contextoAplicacion.onClickJavaScript}"
                    onDblClick="#{ApplicationBean1.contextoAplicacion.onDblClickJavaScript}"
                    onKeyPress="#{ApplicationBean1.contextoAplicacion.onKeyPressJavaScript}"
                    onLoad="#{ApplicationBean1.contextoAplicacion.onLoadJavaScript}"
                    onUnload="#{ApplicationBean1.contextoAplicacion.onUnloadJavaScript}"
                    preserveFocus="#{GrupoAplicacion2.gestor.preserveFocus}"
                    preserveScroll="#{GrupoAplicacion2.gestor.preserveScroll}"
                    styleClass="pdq-body-1">
                    <webuijsf:form 
                        binding="#{GrupoAplicacion2.form1}" 
                        id="form1" 
                        virtualFormsConfig="virtualForm1 | campoIdGrupoAplicacion1 campoCodigoGrupoAplicacion1 campoNombreGrupoAplicacion1 campoDescripcionGrupoAplicacion1 listaFuncionEdicion1 listaFuncionAccion1 | , virtualForm2 | | , virtualForm3 | listaFuncionEdicion1 listaFuncionAccion1 | listaFuncionEdicion1 listaFuncionAccion1 botonEditar1 botonDeshacer1 botonEliminar1 , virtualForm4 | | botonAgregar1 botonDescartar1 botonRefrescar1 botonReconsultar1 botonRetornar1 ">
                        <div class="pos-div-cab-1">
                            <jsp:directive.include file="FragmentoCabeza1.jspf"/>
                        </div>
                        <div class="pos-div-cab-2">
                            <jsp:directive.include file="FragmentoCabeza2.jspf"/>
                        </div>
                        <div class="pos-div-fork">
                            <div class="pos-div-col-izq">
                                <jsp:directive.include file="FragmentoColumnaIzquierda.jspf"/>
                            </div>
                            <div class="pos-div-col-der">
                                <div class="pos-div-cab-3">
                                    <jsp:directive.include file="FragmentoCabeza3.jspf"/>
                                    <webuijsf:breadcrumbs 
                                        binding="#{GrupoAplicacion2.breadcrumbs1}" 
                                        id="breadcrumbs1" 
                                        styleClass="pdq-breadcrumbs-1"/>
                                </div>
                                <div class="pos-div-detalle">
                                    <h:panelGrid 
                                        id="gridPanel101">
                                        <h:panelGrid 
                                            id="gridPanel102">
                                            <h:panelGrid 
                                                columns="2" 
                                                id="gridPanel103">
                                                <webuijsf:image
                                                    id="imagenMensaje1"
                                                    rendered="#{GrupoAplicacion2.gestor.urlImagenSeveridadMensajeDisponible}"
                                                    url="#{GrupoAplicacion2.gestor.urlImagenSeveridadMensaje}"/>
                                                <webuijsf:imageHyperlink
                                                    align="middle"
                                                    id="hipervinculoMensaje1"
                                                    rendered="#{GrupoAplicacion2.gestor.mensajeDisponible}"
                                                    text="#{GrupoAplicacion2.gestor.mensaje}"
                                                    url="#{GrupoAplicacion2.gestor.urlAnclaPie1}"/>
                                            </h:panelGrid>
                                        </h:panelGrid>
                                        <h:panelGrid
                                            id="gridPanel104"
                                            rendered="#{GrupoAplicacion2.gestor.filaDisponible}"
                                            styleClass="pdq-grid-detalle-1">
                                        <h:panelGrid
                                            id="gridPanel105"
                                            styleClass="pdq-grid-detalle-cab">
                                        <h:panelGrid
                                            columns="2"
                                            id="gridPanel106">
                                            <h:panelGrid
                                                id="gridPanel107"
                                                styleClass="pdq-grid-detalle-botones">
                                                <h:panelGrid 
                                                    columns="7"
                                                    id="gridPanel108">
                                                    <webuijsf:button
                                                        actionExpression="#{GrupoAplicacion2.botonIrAlPrimero1_action}"
                                                        binding="#{GrupoAplicacion2.botonIrAlPrimero1}"
                                                        disabled="#{GrupoAplicacion2.gestor.loteSinFilas}"
                                                        id="botonIrAlPrimero1"
                                                        imageURL="#{GrupoAplicacion2.gestor.urlImagenIrAlPrimero}"
                                                        onClick="#{GrupoAplicacion2.gestor.scriptIrAlPrimero}"
                                                        text="#{GrupoAplicacion2.gestor.i18n.textoBotonIrAlPrimero}"
                                                        toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonIrAlPrimero}"/>
                                                    <webuijsf:button
                                                        actionExpression="#{GrupoAplicacion2.botonIrAlAnterior1_action}"
                                                        binding="#{GrupoAplicacion2.botonIrAlAnterior1}"
                                                        disabled="#{GrupoAplicacion2.gestor.loteSinFilas}"
                                                        id="botonIrAlAnterior1"
                                                        imageURL="#{GrupoAplicacion2.gestor.urlImagenIrAlAnterior}"
                                                        onClick="#{GrupoAplicacion2.gestor.scriptIrAlAnterior}"
                                                        text="#{GrupoAplicacion2.gestor.i18n.textoBotonIrAlAnterior}"
                                                        toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonIrAlAnterior}"/>
                                                    <webuijsf:button
                                                        actionExpression="#{GrupoAplicacion2.botonIrAlSiguiente1_action}"
                                                        binding="#{GrupoAplicacion2.botonIrAlSiguiente1}"
                                                        disabled="#{GrupoAplicacion2.gestor.loteSinFilas}"
                                                        id="botonIrAlSiguiente1"
                                                        imageURL="#{GrupoAplicacion2.gestor.urlImagenIrAlSiguiente}"
                                                        onClick="#{GrupoAplicacion2.gestor.scriptIrAlSiguiente}"
                                                        text="#{GrupoAplicacion2.gestor.i18n.textoBotonIrAlSiguiente}"
                                                        toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonIrAlSiguiente}"/>
                                                    <webuijsf:button
                                                        actionExpression="#{GrupoAplicacion2.botonIrAlUltimo1_action}"
                                                        binding="#{GrupoAplicacion2.botonIrAlUltimo1}"
                                                        disabled="#{GrupoAplicacion2.gestor.loteSinFilas}"
                                                        id="botonIrAlUltimo1"
                                                        imageURL="#{GrupoAplicacion2.gestor.urlImagenIrAlUltimo}"
                                                        onClick="#{GrupoAplicacion2.gestor.scriptIrAlUltimo}"
                                                        text="#{GrupoAplicacion2.gestor.i18n.textoBotonIrAlUltimo}"
                                                        toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonIrAlUltimo}"/>
                                                    <webuijsf:button
                                                        actionExpression="#{GrupoAplicacion2.botonProcesarFila1_action}"
                                                        binding="#{GrupoAplicacion2.botonProcesarFila1}"
                                                        disabled="#{GrupoAplicacion2.gestor.funcionPickItemInhabilitada}"
                                                        id="botonProcesarFila1"
                                                        imageURL="#{GrupoAplicacion2.gestor.urlImagenProcesar}"
                                                        onClick="#{GrupoAplicacion2.scriptAbrirVentanaProcesarFila1}"
                                                        rendered="#{GrupoAplicacion2.asistente.comandoDisponible}"
                                                        text="#{GrupoAplicacion2.gestor.i18n.textoBotonProcesarFila}"
                                                        toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonProcesarFila}"/>
                                                </h:panelGrid>
                                            </h:panelGrid>
                                            <h:panelGrid
                                                id="gridPanel109"
                                                styleClass="pdq-grid-detalle-mensajes">
                                                <h:panelGrid
                                                    id="gridPanel110"
                                                    styleClass="pdq-grid-detalle-mensajes-2">
                                                    <webuijsf:staticText
                                                        id="textoTituloConsulta1"
                                                        styleClass="pdq-text-titulo-1"
                                                        text="#{GrupoAplicacion2.gestor.tituloConsulta}"/>
                                                </h:panelGrid>
                                            </h:panelGrid>
                                        </h:panelGrid>
                                        </h:panelGrid>
                                        <h:panelGrid
                                            columns="2"
                                            id="gridPanel111">
                                            <h:panelGrid
                                                id="gridPanel112"
                                                styleClass="pdq-grid-etiqueta-1">
                                                <webuijsf:label
                                                    binding="#{GrupoAplicacion2.etiquetaIdentificacionFila1}"
                                                    id="etiquetaIdentificacionFila1"
                                                    text="#{GrupoAplicacion2.gestor.i18n.textoEtiquetaIdentificacionFila}"
                                                    toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipEtiquetaIdentificacionFila}"/>
                                            </h:panelGrid>
                                            <h:panelGrid
                                                columns="7"
                                                id="gridPanel113"
                                                styleClass="pdq-grid-elemento-1">
                                                <webuijsf:staticText
                                                    id="textoIdentificacionFila1"
                                                    style="font-weight: bold"
                                                    text="#{GrupoAplicacion2.gestor.identificacionFila}"/>
                                                <webuijsf:image
                                                    id="imagenFilaProcesada1"
                                                    toolTip="#{GrupoAplicacion2.gestor.toolTipImagenFilaProcesada}"
                                                    url="#{GrupoAplicacion2.gestor.urlImagenFilaProcesada}"/>
                                            </h:panelGrid>
                                            <h:panelGrid
                                                id="gridPanel114"
                                                rendered="#{GrupoAplicacion2.gestor.designing}"
                                                styleClass="pdq-grid-etiqueta-1">
                                                <webuijsf:label
                                                    binding="#{GrupoAplicacion2.etiquetaDenominacionFilaMaestro1}"
                                                    id="etiquetaDenominacionFilaMaestro1"
                                                    text="?"/>
                                            </h:panelGrid>
                                            <h:panelGrid
                                                columns="7"
                                                id="gridPanel115"
                                                rendered="#{GrupoAplicacion2.gestor.designing}"
                                                styleClass="pdq-grid-elemento-1">
                                                <webuijsf:staticText
                                                    id="textoDenominacionFilaMaestro1"
                                                    style="font-weight: bold"
                                                    text="#{GrupoAplicacion2.gestor.denominacionFilaMaestro}"/>
                                                <webuijsf:image
                                                    id="imagenFilaMaestro1"
                                                    url="#{GrupoAplicacion2.gestor.urlImagenMaestroFilaProcesada}"/>
                                            </h:panelGrid>
                                            <h:panelGrid
                                                id="gridIdGrupoAplicacion1"
                                                styleClass="pdq-grid-etiqueta-1">
                                                <webuijsf:label
                                                    binding="#{GrupoAplicacion2.labelIdGrupoAplicacion1}"
                                                    id="labelIdGrupoAplicacion1"
                                                    for="campoIdGrupoAplicacion1"
                                                    text="id"/>
                                            </h:panelGrid>
                                            <h:panelGrid
                                                columns="7"
                                                id="gridIdGrupoAplicacion2"
                                                styleClass="pdq-grid-elemento-1">
                                                <webuijsf:textField id="campoIdGrupoAplicacion1"
                                                    binding="#{GrupoAplicacion2.campoIdGrupoAplicacion1}"
                                                    converter="#{GrupoAplicacion2.converterIdGrupoAplicacion1}"
                                                    readOnly="#{GrupoAplicacion2.gestor.filaNoProcesada}" required="true"
                                                    text="#{GrupoAplicacion2.grupoAplicacionDataProvider.value['id_grupo_aplicacion']}"
                                                    toolTip="BundleParametros.id_grupo_aplicacion.grupo_aplicacion"
                                                    validatorExpression="#{GrupoAplicacion2.validatorIdGrupoAplicacion1.validate}"/>
                                                <webuijsf:staticText id="campoIdGrupoAplicacion1Texto1"
                                                    binding="#{GrupoAplicacion2.campoIdGrupoAplicacion1Texto1}"
                                                    text="#{GrupoAplicacion2.grupoAplicacionDataProvider.value['id_grupo_aplicacion']}"/>
                                                <webuijsf:message id="messageIdGrupoAplicacion1"
                                                    for="campoIdGrupoAplicacion1"/>
                                                <webuijsf:helpInline id="helpInlineIdGrupoAplicacion1"
                                                    binding="#{GrupoAplicacion2.helpInlineIdGrupoAplicacion1}"
                                                    rendered="#{SessionBean1.contextoSesion.helpInlineRendered}"
                                                    styleClass="pdq-helpInline-field"
                                                    text="BundleParametros.id_grupo_aplicacion.grupo_aplicacion"
                                                    type="field"/>
                                            </h:panelGrid>
                                            <h:panelGrid
                                                id="gridCodigoGrupoAplicacion1"
                                                styleClass="pdq-grid-etiqueta-1">
                                                <webuijsf:label
                                                    binding="#{GrupoAplicacion2.labelCodigoGrupoAplicacion1}"
                                                    id="labelCodigoGrupoAplicacion1"
                                                    for="campoCodigoGrupoAplicacion1"
                                                    text="codigo"/>
                                            </h:panelGrid>
                                            <h:panelGrid
                                                columns="7"
                                                id="gridCodigoGrupoAplicacion2"
                                                styleClass="pdq-grid-elemento-1">
                                                <webuijsf:textField id="campoCodigoGrupoAplicacion1"
                                                    binding="#{GrupoAplicacion2.campoCodigoGrupoAplicacion1}"
                                                    columns="20"
                                                    maxLength="30"
                                                    readOnly="#{GrupoAplicacion2.gestor.filaNoProcesada}" required="true"
                                                    text="#{GrupoAplicacion2.grupoAplicacionDataProvider.value['codigo_grupo_aplicacion']}"
                                                    toolTip="BundleParametros.codigo_grupo_aplicacion.grupo_aplicacion"
                                                    validatorExpression="#{GrupoAplicacion2.validatorCodigoGrupoAplicacion1.validate}"/>
                                                <webuijsf:staticText id="campoCodigoGrupoAplicacion1Texto1"
                                                    binding="#{GrupoAplicacion2.campoCodigoGrupoAplicacion1Texto1}"
                                                    text="#{GrupoAplicacion2.grupoAplicacionDataProvider.value['codigo_grupo_aplicacion']}"/>
                                                <webuijsf:message id="messageCodigoGrupoAplicacion1"
                                                    for="campoCodigoGrupoAplicacion1"/>
                                                <webuijsf:helpInline id="helpInlineCodigoGrupoAplicacion1"
                                                    binding="#{GrupoAplicacion2.helpInlineCodigoGrupoAplicacion1}"
                                                    rendered="#{SessionBean1.contextoSesion.helpInlineRendered}"
                                                    styleClass="pdq-helpInline-field"
                                                    text="BundleParametros.codigo_grupo_aplicacion.grupo_aplicacion"
                                                    type="field"/>
                                            </h:panelGrid>
                                            <h:panelGrid
                                                id="gridNombreGrupoAplicacion1"
                                                styleClass="pdq-grid-etiqueta-1">
                                                <webuijsf:label
                                                    binding="#{GrupoAplicacion2.labelNombreGrupoAplicacion1}"
                                                    id="labelNombreGrupoAplicacion1"
                                                    for="campoNombreGrupoAplicacion1"
                                                    text="nombre"/>
                                            </h:panelGrid>
                                            <h:panelGrid
                                                columns="7"
                                                id="gridNombreGrupoAplicacion2"
                                                styleClass="pdq-grid-elemento-1">
                                                <webuijsf:textField id="campoNombreGrupoAplicacion1"
                                                    binding="#{GrupoAplicacion2.campoNombreGrupoAplicacion1}"
                                                    columns="50"
                                                    maxLength="100"
                                                    readOnly="#{GrupoAplicacion2.gestor.filaNoProcesada}"
                                                    text="#{GrupoAplicacion2.grupoAplicacionDataProvider.value['nombre_grupo_aplicacion']}"
                                                    toolTip="BundleParametros.nombre_grupo_aplicacion.grupo_aplicacion"
                                                    validatorExpression="#{GrupoAplicacion2.validatorNombreGrupoAplicacion1.validate}"/>
                                                <webuijsf:staticText id="campoNombreGrupoAplicacion1Texto1"
                                                    binding="#{GrupoAplicacion2.campoNombreGrupoAplicacion1Texto1}"
                                                    text="#{GrupoAplicacion2.grupoAplicacionDataProvider.value['nombre_grupo_aplicacion']}"/>
                                                <webuijsf:message id="messageNombreGrupoAplicacion1"
                                                    for="campoNombreGrupoAplicacion1"/>
                                                <webuijsf:helpInline id="helpInlineNombreGrupoAplicacion1"
                                                    binding="#{GrupoAplicacion2.helpInlineNombreGrupoAplicacion1}"
                                                    rendered="#{SessionBean1.contextoSesion.helpInlineRendered}"
                                                    styleClass="pdq-helpInline-field"
                                                    text="BundleParametros.nombre_grupo_aplicacion.grupo_aplicacion"
                                                    type="field"/>
                                            </h:panelGrid>
                                            <h:panelGrid
                                                id="gridDescripcionGrupoAplicacion1"
                                                styleClass="pdq-grid-etiqueta-1">
                                                <webuijsf:label
                                                    binding="#{GrupoAplicacion2.labelDescripcionGrupoAplicacion1}"
                                                    id="labelDescripcionGrupoAplicacion1"
                                                    for="campoDescripcionGrupoAplicacion1"
                                                    text="descripcion"/>
                                            </h:panelGrid>
                                            <h:panelGrid
                                                columns="7"
                                                id="gridDescripcionGrupoAplicacion2"
                                                styleClass="pdq-grid-elemento-1">
                                                <webuijsf:textArea id="campoDescripcionGrupoAplicacion1"
                                                    binding="#{GrupoAplicacion2.campoDescripcionGrupoAplicacion1}"
                                                    columns="100" rows="3"
                                                    readOnly="#{GrupoAplicacion2.gestor.filaNoProcesada}"
                                                    text="#{GrupoAplicacion2.grupoAplicacionDataProvider.value['descripcion_grupo_aplicacion']}"
                                                    toolTip="BundleParametros.descripcion_grupo_aplicacion.grupo_aplicacion"
                                                    validatorExpression="#{GrupoAplicacion2.validatorDescripcionGrupoAplicacion1.validate}"/>
                                                <webuijsf:staticText id="campoDescripcionGrupoAplicacion1Texto1"
                                                    binding="#{GrupoAplicacion2.campoDescripcionGrupoAplicacion1Texto1}"
                                                    text="#{GrupoAplicacion2.grupoAplicacionDataProvider.value['descripcion_grupo_aplicacion']}"/>
                                                <webuijsf:message id="messageDescripcionGrupoAplicacion1"
                                                    for="campoDescripcionGrupoAplicacion1"/>
                                                <webuijsf:helpInline id="helpInlineDescripcionGrupoAplicacion1"
                                                    binding="#{GrupoAplicacion2.helpInlineDescripcionGrupoAplicacion1}"
                                                    rendered="#{SessionBean1.contextoSesion.helpInlineRendered}"
                                                    styleClass="pdq-helpInline-field"
                                                    text="BundleParametros.descripcion_grupo_aplicacion.grupo_aplicacion"
                                                    type="field"/>
                                            </h:panelGrid>
                                        </h:panelGrid>
                                        <h:panelGrid
                                            id="gridPanel116"
                                            styleClass="pdq-grid-detalle-pie">
                                        <h:panelGrid
                                            columns="2"
                                            id="gridPanel117">
                                            <h:panelGrid
                                                id="gridPanel118"
                                                styleClass="pdq-grid-detalle-botones">
                                                <h:panelGrid 
                                                    columns="7"
                                                    id="gridPanel119">
                                                    <webuijsf:button
                                                        actionExpression="#{GrupoAplicacion2.botonIrAlPrimero2_action}"
                                                        binding="#{GrupoAplicacion2.botonIrAlPrimero2}"
                                                        disabled="#{GrupoAplicacion2.gestor.loteSinFilas}"
                                                        id="botonIrAlPrimero2"
                                                        imageURL="#{GrupoAplicacion2.gestor.urlImagenIrAlPrimero}"
                                                        onClick="#{GrupoAplicacion2.gestor.scriptIrAlPrimero}"
                                                        text="#{GrupoAplicacion2.gestor.i18n.textoBotonIrAlPrimero}"
                                                        toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonIrAlPrimero}"/>
                                                    <webuijsf:button
                                                        actionExpression="#{GrupoAplicacion2.botonIrAlAnterior2_action}"
                                                        binding="#{GrupoAplicacion2.botonIrAlAnterior2}"
                                                        disabled="#{GrupoAplicacion2.gestor.loteSinFilas}"
                                                        id="botonIrAlAnterior2"
                                                        imageURL="#{GrupoAplicacion2.gestor.urlImagenIrAlAnterior}"
                                                        onClick="#{GrupoAplicacion2.gestor.scriptIrAlAnterior}"
                                                        text="#{GrupoAplicacion2.gestor.i18n.textoBotonIrAlAnterior}"
                                                        toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonIrAlAnterior}"/>
                                                    <webuijsf:button
                                                        actionExpression="#{GrupoAplicacion2.botonIrAlSiguiente2_action}"
                                                        binding="#{GrupoAplicacion2.botonIrAlSiguiente2}"
                                                        disabled="#{GrupoAplicacion2.gestor.loteSinFilas}"
                                                        id="botonIrAlSiguiente2"
                                                        imageURL="#{GrupoAplicacion2.gestor.urlImagenIrAlSiguiente}"
                                                        onClick="#{GrupoAplicacion2.gestor.scriptIrAlSiguiente}"
                                                        text="#{GrupoAplicacion2.gestor.i18n.textoBotonIrAlSiguiente}"
                                                        toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonIrAlSiguiente}"/>
                                                    <webuijsf:button
                                                        actionExpression="#{GrupoAplicacion2.botonIrAlUltimo2_action}"
                                                        binding="#{GrupoAplicacion2.botonIrAlUltimo2}"
                                                        disabled="#{GrupoAplicacion2.gestor.loteSinFilas}"
                                                        id="botonIrAlUltimo2"
                                                        imageURL="#{GrupoAplicacion2.gestor.urlImagenIrAlUltimo}"
                                                        onClick="#{GrupoAplicacion2.gestor.scriptIrAlUltimo}"
                                                        text="#{GrupoAplicacion2.gestor.i18n.textoBotonIrAlUltimo}"
                                                        toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonIrAlUltimo}"/>
                                                    <webuijsf:button
                                                        actionExpression="#{GrupoAplicacion2.botonProcesarFila2_action}"
                                                        binding="#{GrupoAplicacion2.botonProcesarFila2}"
                                                        disabled="#{GrupoAplicacion2.gestor.funcionPickItemInhabilitada}"
                                                        id="botonProcesarFila2"
                                                        imageURL="#{GrupoAplicacion2.gestor.urlImagenProcesar}"
                                                        onClick="#{GrupoAplicacion2.scriptAbrirVentanaProcesarFila2}"
                                                        rendered="#{GrupoAplicacion2.asistente.comandoDisponible}"
                                                        text="#{GrupoAplicacion2.gestor.i18n.textoBotonProcesarFila}"
                                                        toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonProcesarFila}"/>
                                                </h:panelGrid>
                                            </h:panelGrid>
                                            <h:panelGrid
                                                id="gridPanel120"
                                                styleClass="pdq-grid-detalle-mensajes">
                                                <h:panelGrid
                                                    id="gridPanel121"
                                                    styleClass="pdq-grid-detalle-mensajes-2">
                                                    <webuijsf:staticText
                                                        id="textoMensajeCambiosPorConfirmar1"
                                                        style="font-weight: bold"
                                                        text="#{GrupoAplicacion2.gestor.mensajeCambiosPorConfirmar}"/>
                                                </h:panelGrid>
                                            </h:panelGrid>
                                        </h:panelGrid>
                                        </h:panelGrid>
                                        </h:panelGrid>
                                        <h:panelGrid 
                                            id="gridPanel122">
                                            <h:panelGrid 
                                                id="gridPanel123">
                                                <webuijsf:anchor 
                                                    id="anchor1"/>
                                            </h:panelGrid>
                                            <h:panelGrid
                                                columns="13"
                                                id="gridPanel124">
                                                <webuijsf:button
                                                    actionExpression="#{GrupoAplicacion2.botonAgregar1_action}"
                                                    binding="#{GrupoAplicacion2.botonAgregar1}"
                                                    disabled="#{GrupoAplicacion2.gestor.funcionInsertInhabilitada}"
                                                    id="botonAgregar1"
                                                    onClick="#{GrupoAplicacion2.gestor.scriptAgregar}"
                                                    rendered="#{GrupoAplicacion2.gestor.funcionInsertHabilitada}"
                                                    styleClass="pdq-button-1"
                                                    text="#{GrupoAplicacion2.gestor.i18n.textoBotonAgregar}"
                                                    toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonAgregar}"/>
                                                <webuijsf:dropDown
                                                    binding="#{GrupoAplicacion2.listaFuncionEdicion1}"
                                                    converter="#{GrupoAplicacion2.converterListaFuncionEdicion1}"
                                                    disabled="#{GrupoAplicacion2.gestor.loteConCambios}"
                                                    id="listaFuncionEdicion1"
                                                    items="#{GrupoAplicacion2.opcionesListaFuncionEdicion}"
                                                    onChange="webui.suntheme.common.timeoutSubmitForm(this.form, 'listaFuncionEdicion1');"
                                                    rendered="#{GrupoAplicacion2.gestor.edicionMultiFuncionHabilitada}"
                                                    selected="#{GrupoAplicacion2.gestor.funcionEdicionSeleccionada}"
                                                    toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipListaFuncionEdicion}"/>
                                                <webuijsf:button
                                                    actionExpression="#{GrupoAplicacion2.botonEditar1_action}"
                                                    binding="#{GrupoAplicacion2.botonEditar1}"
                                                    disabled="#{GrupoAplicacion2.gestor.funcionUpdateInhabilitada}"
                                                    id="botonEditar1"
                                                    onClick="#{GrupoAplicacion2.gestor.scriptEditar}"
                                                    rendered="#{GrupoAplicacion2.gestor.funcionUpdateHabilitada}"
                                                    styleClass="pdq-button-1"
                                                    text="#{GrupoAplicacion2.gestor.etiquetaOpcionSeleccionadaListaFuncionEdicion}"
                                                    toolTip="#{GrupoAplicacion2.gestor.etiquetaOpcionSeleccionadaListaFuncionEdicion}"/>
                                                <webuijsf:button
                                                    actionExpression="#{GrupoAplicacion2.botonEliminar1_action}"
                                                    binding="#{GrupoAplicacion2.botonEliminar1}"
                                                    disabled="#{GrupoAplicacion2.gestor.funcionDeleteInhabilitada}"
                                                    id="botonEliminar1"
                                                    onClick="#{GrupoAplicacion2.gestor.scriptEliminar}"
                                                    rendered="#{GrupoAplicacion2.gestor.funcionDeleteHabilitada}"
                                                    styleClass="pdq-button-1"
                                                    text="#{GrupoAplicacion2.gestor.i18n.textoBotonEliminar}"
                                                    toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonEliminar}"/>
                                                <webuijsf:button
                                                    actionExpression="#{GrupoAplicacion2.botonAplicar1_action}"
                                                    binding="#{GrupoAplicacion2.botonAplicar1}"
                                                    id="botonAplicar1"
                                                    onClick="#{GrupoAplicacion2.gestor.scriptAplicar}"
                                                    rendered="#{GrupoAplicacion2.gestor.funcionCheckChangesHabilitada}"
                                                    styleClass="pdq-button-1"
                                                    text="#{GrupoAplicacion2.gestor.i18n.textoBotonAplicar}"
                                                    toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonAplicar}"/>
                                                <webuijsf:button
                                                    actionExpression="#{GrupoAplicacion2.botonDeshacer1_action}"
                                                    binding="#{GrupoAplicacion2.botonDeshacer1}"
                                                    id="botonDeshacer1"
                                                    onClick="#{GrupoAplicacion2.gestor.scriptDeshacer}"
                                                    rendered="#{GrupoAplicacion2.gestor.funcionCancelUpdateHabilitada}"
                                                    styleClass="pdq-button-1"
                                                    text="#{GrupoAplicacion2.gestor.i18n.textoBotonDeshacer}"
                                                    toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonDeshacer}"/>
                                                <webuijsf:button
                                                    actionExpression="#{GrupoAplicacion2.botonConfirmar1_action}"
                                                    binding="#{GrupoAplicacion2.botonConfirmar1}"
                                                    id="botonConfirmar1"
                                                    onClick="#{GrupoAplicacion2.gestor.scriptConfirmar}"
                                                    rendered="#{GrupoAplicacion2.gestor.funcionCommitHabilitada}"
                                                    styleClass="pdq-button-1"
                                                    text="#{GrupoAplicacion2.gestor.i18n.textoBotonConfirmar}"
                                                    toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonConfirmar}"/>
                                                <webuijsf:button
                                                    actionExpression="#{GrupoAplicacion2.botonDescartar1_action}"
                                                    binding="#{GrupoAplicacion2.botonDescartar1}"
                                                    id="botonDescartar1"
                                                    onClick="#{GrupoAplicacion2.gestor.scriptDescartar}"
                                                    rendered="#{GrupoAplicacion2.gestor.funcionRevertHabilitada}"
                                                    styleClass="pdq-button-1"
                                                    text="#{GrupoAplicacion2.gestor.i18n.textoBotonDescartar}"
                                                    toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonDescartar}"/>
                                                <webuijsf:dropDown
                                                    binding="#{GrupoAplicacion2.listaFuncionAccion1}"
                                                    converter="#{GrupoAplicacion2.converterListaFuncionAccion1}"
                                                    id="listaFuncionAccion1"
                                                    items="#{GrupoAplicacion2.opcionesListaFuncionAccion}"
                                                    onChange="webui.suntheme.common.timeoutSubmitForm(this.form, 'listaFuncionAccion1');"
                                                    rendered="#{GrupoAplicacion2.gestor.accionMultiFuncionHabilitada}"
                                                    selected="#{GrupoAplicacion2.gestor.funcionAccionSeleccionada}"
                                                    toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipListaFuncionAccion}"/>
                                                <webuijsf:button
                                                    actionExpression="#{GrupoAplicacion2.botonProcesar1_action}"
                                                    binding="#{GrupoAplicacion2.botonProcesar1}"
                                                    id="botonProcesar1"
                                                    onClick="#{GrupoAplicacion2.gestor.scriptProcesar}"
                                                    rendered="#{GrupoAplicacion2.gestor.funcionExecuteHabilitada}"
                                                    styleClass="pdq-button-1"
                                                    text="#{GrupoAplicacion2.gestor.i18n.textoBotonProcesar}"
                                                    toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonProcesar}"/>
                                                <webuijsf:button
                                                    actionExpression="#{GrupoAplicacion2.botonRefrescar1_action}"
                                                    binding="#{GrupoAplicacion2.botonRefrescar1}"
                                                    disabled="#{GrupoAplicacion2.gestor.funcionSelectInhabilitada}"
                                                    id="botonRefrescar1"
                                                    onClick="#{GrupoAplicacion2.gestor.scriptRefrescar}"
                                                    rendered="#{GrupoAplicacion2.gestor.funcionRefreshHabilitada}"
                                                    styleClass="pdq-button-1"
                                                    text="#{GrupoAplicacion2.gestor.i18n.textoBotonRefrescar}"
                                                    toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonRefrescar}"/>
                                                <webuijsf:button
                                                    actionExpression="#{GrupoAplicacion2.botonReconsultar1_action}"
                                                    binding="#{GrupoAplicacion2.botonReconsultar1}"
                                                    disabled="#{GrupoAplicacion2.gestor.funcionSelectInhabilitada}"
                                                    id="botonReconsultar1"
                                                    onClick="#{GrupoAplicacion2.gestor.scriptReconsultar}"
                                                    rendered="#{GrupoAplicacion2.gestor.funcionRequeryHabilitada}"
                                                    styleClass="pdq-button-1"
                                                    text="#{GrupoAplicacion2.gestor.i18n.textoBotonReconsultar}"
                                                    toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonReconsultar}"/>
                                                <webuijsf:button
                                                    actionExpression="#{GrupoAplicacion2.botonRetornar1_action}"
                                                    binding="#{GrupoAplicacion2.botonRetornar1}"
                                                    disabled="#{GrupoAplicacion2.gestor.funcionReturnFilaEscogidaInhabilitada}"
                                                    id="botonRetornar1"
                                                    onClick="#{GrupoAplicacion2.gestor.scriptRetornarRecursoEscogido}"
                                                    rendered="#{GrupoAplicacion2.gestor.funcionReturnVisible}"
                                                    styleClass="pdq-button-1"
                                                    text="#{GrupoAplicacion2.gestor.i18n.textoBotonRetornar}"
                                                    toolTip="#{GrupoAplicacion2.gestor.i18n.toolTipBotonRetornar}"/>
                                            </h:panelGrid>
                                            <h:panelGrid 
                                                columns="2" 
                                                id="gridPanel125"
                                                rendered="#{GrupoAplicacion2.gestor.funcionOpenLinkHabilitada}">
                                                <webuijsf:imageHyperlink
                                                    actionExpression="#{GrupoAplicacion2.imageHyperlink1_action}"
                                                    binding="#{GrupoAplicacion2.imageHyperlink1}"
                                                    disabled="#{GrupoAplicacion2.gestor.funcionOpenLinkInhabilitada}"
                                                    id="imageHyperlink1"
                                                    imageURL="#{GrupoAplicacion2.gestor.urlImagenAbrirVinculo}"
                                                    onClick="#{GrupoAplicacion2.gestor.scriptAbrirVinculo}"
                                                    styleClass="pdq-hyperlink-1"
                                                    text="Hyperlink1"
                                                    toolTip="#{bundle.GrupoAplicacion2_imageHyperlink1_toolTip}"/>
                                                <webuijsf:imageHyperlink
                                                    actionExpression="#{GrupoAplicacion2.imageHyperlink2_action}"
                                                    binding="#{GrupoAplicacion2.imageHyperlink2}"
                                                    disabled="#{GrupoAplicacion2.gestor.funcionOpenLinkInhabilitada}"
                                                    id="imageHyperlink2"
                                                    imageURL="#{GrupoAplicacion2.gestor.urlImagenAbrirVinculo}"
                                                    onClick="#{GrupoAplicacion2.gestor.scriptAbrirVinculo}"
                                                    styleClass="pdq-hyperlink-1"
                                                    rendered="#{GrupoAplicacion2.gestor.designing}"
                                                    text="Hyperlink2"
                                                    toolTip="#{bundle.GrupoAplicacion2_imageHyperlink2_toolTip}"/>
                                            </h:panelGrid>
                                        </h:panelGrid>
                                    </h:panelGrid>
                                </div>
                                <div class="pos-div-pie-3">
                                    <jsp:directive.include file="FragmentoPie3.jspf"/>
                                </div>
                            </div>
                            <div class="pos-div-join">
                                <jsp:directive.include file="FragmentoJoin.jspf"/>
                            </div>
                        </div>
                        <div class="pos-div-pie-2">
                            <jsp:directive.include file="FragmentoPie2.jspf"/>
                        </div>
                        <div class="pos-div-pie-1">
                            <jsp:directive.include file="FragmentoPie1.jspf"/>
                        </div>
                        <webuijsf:anchor id="anclaPie1"/>
                    </webuijsf:form>
                </webuijsf:body>
            </webuijsf:html>
        </webuijsf:page>
    </f:view>
</jsp:root>
