ALTER TABLE aplicacion ADD CONSTRAINT UQ_aplicacion_0001_ZYX UNIQUE (codigo_aplicacion);
ALTER TABLE archivo_datos_ext ADD CONSTRAINT UQ_archivo_datos_ext_0001_ZYX UNIQUE (codigo_archivo_datos_ext);
ALTER TABLE causa_den_pension ADD CONSTRAINT UQ_causa_den_pension_0001_ZYX UNIQUE (codigo_causa_den_pension);
ALTER TABLE causa_den_recl_cen ADD CONSTRAINT UQ_causa_den_recl_cen_0001_ZYX UNIQUE (codigo_causa_den_recl_cen);
ALTER TABLE causa_den_reco_pen ADD CONSTRAINT UQ_causa_den_reco_pen_0001_ZYX UNIQUE (codigo_causa_den_reco_pen);
ALTER TABLE causa_impedimento ADD CONSTRAINT UQ_causa_impedimento_0001_ZYX UNIQUE (codigo_causa_impedimento);
ALTER TABLE causa_inv_censo ADD CONSTRAINT UQ_causa_inv_censo_0001_ZYX UNIQUE (codigo_causa_inv_censo);
ALTER TABLE causa_rev_pension ADD CONSTRAINT UQ_causa_rev_pension_0001_ZYX UNIQUE (codigo_causa_rev_pension);
ALTER TABLE clase_enf_acc ADD CONSTRAINT UQ_clase_enf_acc_0001_ZYX UNIQUE (codigo_clase_enf_acc);
ALTER TABLE clase_enf_cronica ADD CONSTRAINT UQ_clase_enf_cronica_0001_ZYX UNIQUE (codigo_clase_enf_cronica);
ALTER TABLE clase_impedimento ADD CONSTRAINT UQ_clase_impedimento_0001_ZYX UNIQUE (codigo_clase_impedimento);
ALTER TABLE clase_recurso ADD CONSTRAINT UQ_clase_recurso_0001_ZYX UNIQUE (codigo_clase_recurso);
ALTER TABLE clase_recurso_par ADD CONSTRAINT UQ_clase_recurso_par_0001_ZYX UNIQUE (id_clase_recurso, id_parametro);
ALTER TABLE clase_recurso_sec ADD CONSTRAINT UQ_clase_recurso_sec_0001_ZYX UNIQUE (id_clase_recurso, etiqueta_clase_recurso_sec);
ALTER TABLE condicion_censo ADD CONSTRAINT UQ_condicion_censo_0001_ZYX UNIQUE (codigo_condicion_censo);
ALTER TABLE condicion_denu_pen ADD CONSTRAINT UQ_condicion_denu_pen_0001_ZYX UNIQUE (codigo_condicion_denu_pen);
ALTER TABLE condicion_eje_fun ADD CONSTRAINT UQ_condicion_eje_fun_0001_ZYX UNIQUE (codigo_condicion_eje_fun);
ALTER TABLE condicion_pension ADD CONSTRAINT UQ_condicion_pension_0001_ZYX UNIQUE (codigo_condicion_pension);
ALTER TABLE condicion_recl_cen ADD CONSTRAINT UQ_condicion_recl_cen_0001_ZYX UNIQUE (codigo_condicion_recl_cen);
ALTER TABLE condicion_reco_pen ADD CONSTRAINT UQ_condicion_reco_pen_0001_ZYX UNIQUE (codigo_condicion_reco_pen);
ALTER TABLE conjunto_segmento ADD CONSTRAINT UQ_conjunto_segmento_0001_ZYX UNIQUE (codigo_conjunto_segmento);
ALTER TABLE dominio ADD CONSTRAINT UQ_dominio_0001_ZYX UNIQUE (codigo_dominio);
ALTER TABLE dominio_paquete ADD CONSTRAINT UQ_dominio_paquete_0001_ZYX UNIQUE (id_dominio, id_paquete);
ALTER TABLE dominio_parametro ADD CONSTRAINT UQ_dominio_parametro_0001_ZYX UNIQUE (id_dominio, numero_tipo_parametro_dom);
ALTER TABLE elemento_segmento ADD CONSTRAINT UQ_elemento_segmento_0001_ZYX UNIQUE (id_conjunto_segmento, id_segmento);
ALTER TABLE estado_civil ADD CONSTRAINT UQ_estado_civil_0001_ZYX UNIQUE (codigo_estado_civil);
ALTER TABLE estado_salud ADD CONSTRAINT UQ_estado_salud_0001_ZYX UNIQUE (codigo_estado_salud);
ALTER TABLE etnia_indigena ADD CONSTRAINT UQ_etnia_indigena_0001_ZYX UNIQUE (codigo_etnia_indigena);
ALTER TABLE ficha_hogar ADD CONSTRAINT UQ_ficha_hogar_0001_ZYX UNIQUE (codigo_ficha_hogar);
ALTER TABLE ficha_persona ADD CONSTRAINT UQ_ficha_persona_0001_ZYX UNIQUE (codigo_ficha_persona);
ALTER TABLE ficha_persona ADD CONSTRAINT UQ_ficha_persona_0002_ZYX UNIQUE (id_ficha_hogar, numero_orden_identificacion);
ALTER TABLE filtro_funcion ADD CONSTRAINT UQ_filtro_funcion_0001_ZYX UNIQUE (codigo_filtro_funcion);
ALTER TABLE funcion ADD CONSTRAINT UQ_funcion_0001_ZYX UNIQUE (codigo_funcion);
ALTER TABLE funcion_parametro ADD CONSTRAINT UQ_funcion_parametro_0001_ZYX UNIQUE (id_funcion, id_parametro);
ALTER TABLE funcionario ADD CONSTRAINT UQ_funcionario_0001_ZYX UNIQUE (codigo_funcionario);
ALTER TABLE grupo_aplicacion ADD CONSTRAINT UQ_grupo_aplicacion_0001_ZYX UNIQUE (codigo_grupo_aplicacion);
ALTER TABLE grupo_proceso ADD CONSTRAINT UQ_grupo_proceso_0001_ZYX UNIQUE (codigo_grupo_proceso);
ALTER TABLE idioma_hogar ADD CONSTRAINT UQ_idioma_hogar_0001_ZYX UNIQUE (codigo_idioma_hogar);
ALTER TABLE informe ADD CONSTRAINT UQ_informe_0001_ZYX UNIQUE (codigo_proceso_informe);
ALTER TABLE mensaje ADD CONSTRAINT UQ_mensaje_0001_ZYX UNIQUE (codigo_mensaje);
ALTER TABLE motivo_ina_esc ADD CONSTRAINT UQ_motivo_ina_esc_0001_ZYX UNIQUE (codigo_motivo_ina_esc);
ALTER TABLE motivo_no_atencion ADD CONSTRAINT UQ_motivo_no_atencion_0001_ZYX UNIQUE (codigo_motivo_no_atencion);
ALTER TABLE motivo_no_trabajo ADD CONSTRAINT UQ_motivo_no_trabajo_0001_ZYX UNIQUE (codigo_motivo_no_trabajo);
ALTER TABLE nivel_educativo ADD CONSTRAINT UQ_nivel_educativo_0001_ZYX UNIQUE (codigo_nivel_educativo);
ALTER TABLE nivel_opcion_menu ADD CONSTRAINT UQ_nivel_opcion_menu_0001_ZYX UNIQUE (codigo_nivel_opcion_menu);
ALTER TABLE nivel_ubicacion ADD CONSTRAINT UQ_nivel_ubicacion_0001_ZYX UNIQUE (codigo_nivel_ubicacion);
ALTER TABLE opcion_binaria ADD CONSTRAINT UQ_opcion_binaria_0001_ZYX UNIQUE (codigo_opcion_si_no);
ALTER TABLE opcion_binaria ADD CONSTRAINT UQ_opcion_binaria_0002_ZYX UNIQUE (codigo_opcion_activo_inactivo);
ALTER TABLE opcion_binaria ADD CONSTRAINT UQ_opcion_binaria_0003_ZYX UNIQUE (codigo_opcion_enc_apa);
ALTER TABLE opcion_binaria ADD CONSTRAINT UQ_opcion_binaria_0004_ZYX UNIQUE (codigo_opcion_presente_ausente);
ALTER TABLE opcion_binaria ADD CONSTRAINT UQ_opcion_binaria_0005_ZYX UNIQUE (codigo_opcion_pos_neg);
ALTER TABLE opcion_binaria ADD CONSTRAINT UQ_opcion_binaria_0006_ZYX UNIQUE (codigo_opcion_verdadero_falso);
ALTER TABLE opcion_menu ADD CONSTRAINT UQ_opcion_menu_0001_ZYX UNIQUE (codigo_opcion_menu);
ALTER TABLE operador_com ADD CONSTRAINT UQ_operador_com_0001_ZYX UNIQUE (codigo_operador_com);
ALTER TABLE pagina ADD CONSTRAINT UQ_pagina_0001_ZYX UNIQUE (codigo_pagina, id_aplicacion);
ALTER TABLE pagina_funcion ADD CONSTRAINT UQ_pagina_funcion_0001_ZYX UNIQUE (id_pagina, id_funcion);
ALTER TABLE pagina_usuario ADD CONSTRAINT UQ_pagina_usuario_0001_ZYX UNIQUE (id_pagina, id_usuario);
ALTER TABLE paquete ADD CONSTRAINT UQ_paquete_0001_ZYX UNIQUE (codigo_paquete);
ALTER TABLE parametro ADD CONSTRAINT UQ_parametro_0001_ZYX UNIQUE (codigo_parametro);
ALTER TABLE parametro_global ADD CONSTRAINT UQ_parametro_global_0001_ZYX UNIQUE (codigo_parametro_global);
ALTER TABLE persona ADD CONSTRAINT UQ_persona_0001_ZYX UNIQUE (numero_cedula, letra_cedula);
ALTER TABLE persona ADD CONSTRAINT UQ_persona_0002_ZYX UNIQUE (codigo_persona);
ALTER TABLE potencial_ben ADD CONSTRAINT UQ_potencial_ben_0001_ZYX UNIQUE (codigo_potencial_ben);
ALTER TABLE potencial_ben ADD CONSTRAINT UQ_potencial_ben_0002_ZYX UNIQUE (numero_cedula, letra_cedula);
ALTER TABLE potencial_ben ADD CONSTRAINT UQ_potencial_ben_0003_ZYX UNIQUE (id_persona);
ALTER TABLE proceso ADD CONSTRAINT UQ_proceso_0001_ZYX UNIQUE (codigo_proceso_proceso);
ALTER TABLE proveedor_dat_ext ADD CONSTRAINT UQ_proveedor_dat_ext_0001_ZYX UNIQUE (codigo_proveedor_dat_ext);
ALTER TABLE rol ADD CONSTRAINT UQ_rol_0001_ZYX UNIQUE (codigo_rol);
ALTER TABLE rol_aplicacion ADD CONSTRAINT UQ_rol_aplicacion_0001_ZYX UNIQUE (id_rol, id_aplicacion);
ALTER TABLE rol_filtro_funcion ADD CONSTRAINT UQ_rol_filtro_funcion_0001_ZYX UNIQUE (id_rol, id_filtro_funcion);
ALTER TABLE rol_funcion ADD CONSTRAINT UQ_rol_funcion_0001_ZYX UNIQUE (id_rol, id_funcion);
ALTER TABLE rol_pagina ADD CONSTRAINT UQ_rol_pagina_0001_ZYX UNIQUE (id_rol, id_pagina);
ALTER TABLE rol_usuario ADD CONSTRAINT UQ_rol_usuario_0001_ZYX UNIQUE (id_rol, id_usuario);
ALTER TABLE sexo_persona ADD CONSTRAINT UQ_sexo_persona_0001_ZYX UNIQUE (codigo_sexo_persona);
ALTER TABLE siono ADD CONSTRAINT UQ_siono_0001_ZYX UNIQUE (codigo_siono);
ALTER TABLE tipo_aba_agua ADD CONSTRAINT UQ_tipo_aba_agua_0001_ZYX UNIQUE (codigo_tipo_aba_agua);
ALTER TABLE tipo_act_jupe ADD CONSTRAINT UQ_tipo_act_jupe_0001_ZYX UNIQUE (codigo_tipo_act_jupe);
ALTER TABLE tipo_arc_dat_ext ADD CONSTRAINT UQ_tipo_arc_dat_ext_0001_ZYX UNIQUE (codigo_tipo_arc_dat_ext);
ALTER TABLE tipo_area ADD CONSTRAINT UQ_tipo_area_0001_ZYX UNIQUE (codigo_tipo_area);
ALTER TABLE tipo_clase_recurso ADD CONSTRAINT UQ_tipo_clase_recurso_0001_ZYX UNIQUE (codigo_tipo_clase_recurso);
ALTER TABLE tipo_combustible ADD CONSTRAINT UQ_tipo_combustible_0001_ZYX UNIQUE (codigo_tipo_combustible);
ALTER TABLE tipo_comparacion ADD CONSTRAINT UQ_tipo_comparacion_0001_ZYX UNIQUE (codigo_tipo_comparacion);
ALTER TABLE tipo_dato_par ADD CONSTRAINT UQ_tipo_dato_par_0001_ZYX UNIQUE (codigo_tipo_dato_par);
ALTER TABLE tipo_desecho_bas ADD CONSTRAINT UQ_tipo_desecho_bas_0001_ZYX UNIQUE (codigo_tipo_desecho_bas);
ALTER TABLE tipo_dominio ADD CONSTRAINT UQ_tipo_dominio_0001_ZYX UNIQUE (codigo_tipo_dominio);
ALTER TABLE tipo_excepcion_ced ADD CONSTRAINT UQ_tipo_excepcion_ced_0001_ZYX UNIQUE (codigo_tipo_excepcion_ced);
ALTER TABLE tipo_funcion ADD CONSTRAINT UQ_tipo_funcion_0001_ZYX UNIQUE (codigo_tipo_funcion);
ALTER TABLE tipo_mat_paredes ADD CONSTRAINT UQ_tipo_mat_paredes_0001_ZYX UNIQUE (codigo_tipo_mat_paredes);
ALTER TABLE tipo_mat_piso ADD CONSTRAINT UQ_tipo_mat_piso_0001_ZYX UNIQUE (codigo_tipo_mat_piso);
ALTER TABLE tipo_mat_techo ADD CONSTRAINT UQ_tipo_mat_techo_0001_ZYX UNIQUE (codigo_tipo_mat_techo);
ALTER TABLE tipo_nodo ADD CONSTRAINT UQ_tipo_nodo_0001_ZYX UNIQUE (codigo_tipo_nodo);
ALTER TABLE tipo_obj_ele_pen ADD CONSTRAINT UQ_tipo_obj_ele_pen_0001_ZYX UNIQUE (codigo_tipo_obj_ele_pen);
ALTER TABLE tipo_ocupacion_viv ADD CONSTRAINT UQ_tipo_ocupacion_viv_0001_ZYX UNIQUE (codigo_tipo_ocupacion_viv);
ALTER TABLE tipo_pagina ADD CONSTRAINT UQ_tipo_pagina_0001_ZYX UNIQUE (codigo_tipo_pagina);
ALTER TABLE tipo_parametro ADD CONSTRAINT UQ_tipo_parametro_0001_ZYX UNIQUE (codigo_tipo_parametro);
ALTER TABLE tipo_parametro_dom ADD CONSTRAINT UQ_tipo_parametro_dom_0001_ZYX UNIQUE (codigo_tipo_parametro_dom);
ALTER TABLE tipo_parametro_dom ADD CONSTRAINT UQ_tipo_parametro_dom_0002_ZYX UNIQUE (codigo_propiedad_interfaz);
ALTER TABLE tipo_parametro_dom ADD CONSTRAINT UQ_tipo_parametro_dom_0003_ZYX UNIQUE (nombre_interfaz);
ALTER TABLE tipo_persona_hogar ADD CONSTRAINT UQ_tipo_persona_hogar_0001_ZYX UNIQUE (codigo_tipo_persona_hogar);
ALTER TABLE tipo_pieza_bano ADD CONSTRAINT UQ_tipo_pieza_bano_0001_ZYX UNIQUE (codigo_tipo_pieza_bano);
ALTER TABLE tipo_rastro_fun ADD CONSTRAINT UQ_tipo_rastro_fun_0001_ZYX UNIQUE (codigo_tipo_rastro_fun);
ALTER TABLE tipo_recurso ADD CONSTRAINT UQ_tipo_recurso_0001_ZYX UNIQUE (codigo_tipo_recurso);
ALTER TABLE tipo_reg_pot_ben ADD CONSTRAINT UQ_tipo_reg_pot_ben_0001_ZYX UNIQUE (codigo_tipo_reg_pot_ben);
ALTER TABLE tipo_relacion_lab ADD CONSTRAINT UQ_tipo_relacion_lab_0001_ZYX UNIQUE (codigo_tipo_relacion_lab);
ALTER TABLE tipo_rol ADD CONSTRAINT UQ_tipo_rol_0001_ZYX UNIQUE (codigo_tipo_rol);
ALTER TABLE tipo_seguro_medico ADD CONSTRAINT UQ_tipo_seguro_medico_0001_ZYX UNIQUE (codigo_tipo_seguro_medico);
ALTER TABLE tipo_servicio_agua ADD CONSTRAINT UQ_tipo_servicio_agua_0001_ZYX UNIQUE (codigo_tipo_servicio_agua);
ALTER TABLE tipo_servicio_san ADD CONSTRAINT UQ_tipo_servicio_san_0001_ZYX UNIQUE (codigo_tipo_servicio_san);
ALTER TABLE tipo_valor ADD CONSTRAINT UQ_tipo_valor_0001_ZYX UNIQUE (codigo_tipo_valor);
ALTER TABLE ubicacion ADD CONSTRAINT UQ_ubicacion_0001_ZYX UNIQUE (codigo_ubicacion);
ALTER TABLE usuario ADD CONSTRAINT UQ_usuario_0001_ZYX UNIQUE (codigo_usuario);
