type t_array is table of varchar2(50) index by binary_integer; 
function ext_tipo_area_ubi(str varchar2) return number;
function split (p_in_string varchar2, p_delim varchar2) return t_array;
function extract_id_persona(cedula varchar2, nombre_1 varchar2, nombre_2 varchar2,apellido_1 varchar2, apellido_2 varchar2, apellido_3 varchar2) return number;
function extract_id_funcionario(cedula varchar2) return number;
function extract_id_pot_ben(cedula varchar2, nombre_1 varchar2, nombre_2 varchar2, apellido_1 varchar2, apellido_2 varchar2) return number;
function get_id_barrio(distrito varchar2,barrio varchar2) return number;
function get_id_departamento(departamento varchar2) return number;
function get_id_distrito(departamento varchar2,distrito varchar2) return number;
function get_id_ubicacion(str varchar2) return number;
function get_numero_tipo_area(id_barrio number) return number;
FUNCTION concat_fecha(d varchar2,m varchar2, a varchar2) RETURN timestamp;
function extract_causa_impedimento(str varchar2) return number;
function extract_clase_enf_acc(str varchar2) return number ;
function extract_clase_enf_cronica(str varchar2) return number;
function extract_clase_impedimento(str varchar2) return number;
function extract_codigo_ficha_hogar(p01a varchar2,p01b varchar2,p01c varchar2,p01d varchar2,p02 varchar2,p03 varchar2) return varchar2;
function extract_dispo_aire(str varchar2) return number;
function extract_dispo_auto(str varchar2) return number;
function extract_dispo_camion(str varchar) return number;
function extract_disp_heladera(str varchar2) return number;
function extract_dispo_lavarropas(str varchar2) return number;
function extract_dispo_motocicleta(str varchar2) return number;
function extract_dispo_termo(str varchar2) return number;
function extract_distancia(str1 varchar2) return number;
function extract_es_indigena(str varchar2) return number;
function extract_es_paraguayo(str varchar) return number;
function extract_estado_civil(str1 varchar2) return number;
function extract_estado_salud(str varchar2) return number;
FUNCTION extract_fecha(d varchar2,m varchar2, a varchar2) return timestamp;
function extract_franja_utm(str varchar2) return char;
function extract_huso_utm(str1 varchar2) return number;
function extract_id_barrio(departamento varchar2,distrito varchar2,barrio varchar2) return number;
function extract_id_departamento(departamento varchar2) return number;
function extract_id_distrito(departamento varchar2,distrito varchar2) return number;
function extract_idioma_hogar(str varchar2) return number;
function extract_motivo_ina_esc(str varchar2) return number;
function extract_motivo_no_atencion(str varchar2) return number;
function extract_motivo_no_trabajo(str varchar2) return number;
function extract_nivel_educ(str varchar2) return number;
function extract_numero_formulario(str1 varchar2) return number;
function extract_numero_hogar(str1 varchar2) return number;
function extract_numero_orden_id(str1 varchar2) return number;
function extract_numero_vivienda(str1 varchar2) return number;
function extract_otro_tipo_ocupacion(str1 varchar2,str2 varchar2) return varchar2;
function extract_sexo_ficha_persona(str1 varchar2) return number;
function extract_sexo_persona(str1 varchar2) return number;
function extract_siono(str varchar2) return number;
function extract_telefono(str1 varchar2,str2 varchar2) return varchar2;
function extract_tipo_abastecimiento(str varchar2) return number;
function extract_tipo_area(str varchar2) return number;
function extract_tipo_area_ubicacion(str varchar2) return number;
function extract_tipo_combustible(str varchar2) return number;
function extract_tipo_desecho_bas(str varchar2) return number;
function extract_tipo_mat_paredes(str varchar2) return number;
function extract_tipo_mat_piso(str varchar2) return number;
function extract_tipo_mat_techo(str varchar2) return number;
function extract_tipo_ocupacion(str varchar2) return number;
function extract_tipo_persona_hogar(str1 varchar2) return number;
function extract_tipo_pieza_bano(str varchar2) return number;
function extract_tipo_relacion_lab(str varchar2) return number;
function extract_tipo_seguro_medico(str varchar2) return number;
function extract_tipo_servicio_agua(str varchar2) return number;
function extract_tipo_servicio_san(str varchar2) return number;
function extract_ultimo_curso_aprobado(str varchar2) return number;
function extract_numero_from_cedula(ced varchar2) return number;
function extract_letra_from_cedula(ced varchar2) return char;
function get_id_departamento_sw(departamento varchar2) return number;
function get_id_distrito_sw(departamento varchar2,distrito varchar2) return number;
