type t_array is table of varchar2(50) index by binary_integer; 
function ext_tipo_area_ubi(str varchar2) return number;
function split (p_in_string varchar2, p_delim varchar2) return t_array;
function extract_id_persona(cedula varchar2, nombre_1 varchar2, nombre_2 varchar2,apellido_1 varchar2, apellido_2 varchar2, apellido_3 varchar2) return number;
function get_id_barrio(distrito varchar2,barrio varchar2) return number;
function get_id_departamento(departamento varchar2) return number;
function get_id_distrito(departamento varchar2,distrito varchar2) return number;
function get_id_ubicacion(str varchar2) return number;
function get_numero_tipo_area(id_barrio number) return number;
FUNCTION concat_fecha(d varchar2,m varchar2, a varchar2) RETURN timestamp;
function extract_causa_impedimento(str varchar2) return number;
function extract_clase_enf_acc(str varchar2) return number ;
function extract_clase_enf_cronica(str varchar2) return number;
function extract_clase_impedimento(str varchar2) return number;
function extract_codigo_ficha_hogar(p01a varchar2,p01b varchar2,p01c varchar2,p01d varchar2,p02 varchar2,p03 varchar2) return varchar2;
function extract_dispo_aire(str varchar2) return number;
function extract_dispo_auto(str varchar2) return number;
function extract_dispo_camion(str varchar) return number;
function extract_disp_heladera(str varchar2) return number;
function extract_dispo_lavarropas(str varchar2) return number;
function extract_dispo_motocicleta(str varchar2) return number;
function extract_dispo_termo(str varchar2) return number;
function extract_distancia(str1 varchar2) return number;
function extract_es_indigena(str varchar2) return number;
function extract_es_paraguayo(str varchar) return number;
function extract_estado_civil(str1 varchar2) return number;
function extract_estado_salud(str varchar2) return number;
FUNCTION extract_fecha(d varchar2,m varchar2, a varchar2) return timestamp;
function extract_franja_utm(str varchar2) return char;
function extract_huso_utm(str1 varchar2) return number;
function extract_id_barrio(departamento varchar2,distrito varchar2,barrio varchar2) return number;
function extract_id_departamento(departamento varchar2) return number;
function extract_id_distrito(departamento varchar2,distrito varchar2) return number;

