function csv_org(archivo varchar2, conjunto varchar2, ignorados varchar2, separador varchar2, delimitador varchar2) return varchar2;
procedure create_csv_log_imp_deu(archivo varchar2, conjunto varchar2, ignorados varchar2, separador varchar2, delimitador varchar2);
procedure create_csv_log_imp_emp(archivo varchar2, conjunto varchar2, ignorados varchar2, separador varchar2, delimitador varchar2);
procedure create_csv_log_imp_fal(archivo varchar2, conjunto varchar2, ignorados varchar2, separador varchar2, delimitador varchar2);
procedure create_csv_log_imp_hog(archivo varchar2, conjunto varchar2, ignorados varchar2, separador varchar2, delimitador varchar2);
procedure create_csv_log_imp_ids(archivo varchar2, conjunto varchar2, ignorados varchar2, separador varchar2, delimitador varchar2);
procedure create_csv_log_imp_jub(archivo varchar2, conjunto varchar2, ignorados varchar2, separador varchar2, delimitador varchar2);
procedure create_csv_log_imp_pen(archivo varchar2, conjunto varchar2, ignorados varchar2, separador varchar2, delimitador varchar2);
procedure create_csv_log_imp_per(archivo varchar2, conjunto varchar2, ignorados varchar2, separador varchar2, delimitador varchar2);
procedure create_csv_log_imp_pot(archivo varchar2, conjunto varchar2, ignorados varchar2, separador varchar2, delimitador varchar2);
procedure create_csv_log_imp_sub(archivo varchar2, conjunto varchar2, ignorados varchar2, separador varchar2, delimitador varchar2);
procedure create_csv_log_imp_ubi(archivo varchar2, conjunto varchar2, ignorados varchar2, separador varchar2, delimitador varchar2);
