COMMENT ON TABLE  clase_recurso_par IS '';
COMMENT ON COLUMN clase_recurso_par.es_parametro_omisible IS 'Solo lectura al crear';
COMMENT ON COLUMN clase_recurso_par.es_parametro_inmutable IS 'Solo lectura al modificar';
COMMENT ON COLUMN clase_recurso_par.es_parametro_submit IS 'Auto-Submit on Change';
COMMENT ON TABLE  ficha_hogar IS '';
COMMENT ON COLUMN ficha_hogar.observaciones IS 'Observaciones de campo';
COMMENT ON COLUMN ficha_hogar.huso_utm IS 'Número de Zona ó Huso (1-60) de la ubicación de la vivienda (según GPS)';
COMMENT ON COLUMN ficha_hogar.franja_utm IS 'Banda ó Franja (C-X, sin I ni O) de la ubicación de la vivienda (según GPS)';
COMMENT ON COLUMN ficha_hogar.distancia_este_utm IS 'Coordenada X: distancia horizontal al Este (Easting) de la ubicación de la vivienda (según GPS)';
COMMENT ON COLUMN ficha_hogar.distancia_norte_utm IS 'Coordenada Y: distancia vertical al Norte (Northing) de la ubicación de la vivienda (según GPS)';
COMMENT ON COLUMN ficha_hogar.numero_tipo_area IS 'Tipo de área (urbana o rural)';
COMMENT ON COLUMN ficha_hogar.numero_tipo_mat_paredes IS 'Material predominante en las paredes exteriores';
COMMENT ON COLUMN ficha_hogar.numero_tipo_mat_piso IS 'Material predominante en el piso';
COMMENT ON COLUMN ficha_hogar.numero_tipo_mat_techo IS 'Material predominante en el techo';
COMMENT ON COLUMN ficha_hogar.numero_tipo_ocupacion_viv IS 'Condición de ocupación de la vivienda';
COMMENT ON COLUMN ficha_hogar.otro_tipo_ocupacion_viv IS 'Condición de ocupación de la vivienda (especificar si la respuesta anterior es 6 "Otros")';
COMMENT ON COLUMN ficha_hogar.cantidad_piezas IS 'Número de piezas, sin incluir baño, cocina, cuartos o piezas destinadas exclusivamente al comercio o industria';
COMMENT ON COLUMN ficha_hogar.cantidad_dormitorios IS 'Número de dormitorios';
COMMENT ON COLUMN ficha_hogar.numero_siono_pieza_cocina IS 'Tiene pieza para cocinar';
COMMENT ON COLUMN ficha_hogar.numero_tipo_combustible IS 'Combustible que se utiliza en forma habitual para cocinar';
COMMENT ON COLUMN ficha_hogar.numero_tipo_pieza_bano IS 'Tipo de pieza para bañarse';
COMMENT ON COLUMN ficha_hogar.numero_tipo_servicio_san IS 'Tipo de desagüe que tiene el baño';
COMMENT ON COLUMN ficha_hogar.numero_tipo_servicio_agua IS 'Procedencia del agua que se utiliza en l a vivienda';
COMMENT ON COLUMN ficha_hogar.numero_tipo_aba_agua IS 'Lugar de abastecimiento del agua que se utiliza en l a vivienda';
COMMENT ON COLUMN ficha_hogar.numero_siono_corriente_elec IS 'Dispone de luz eléctrica';
COMMENT ON COLUMN ficha_hogar.numero_tipo_desecho_bas IS 'Forma de desechar la basura';
COMMENT ON COLUMN ficha_hogar.numero_siono_telefono_celular IS 'Tiene teléfono celular';
COMMENT ON COLUMN ficha_hogar.numero_telefono_celular IS 'Número de teléfono celular';
COMMENT ON COLUMN ficha_hogar.numero_siono_tlf_linea_baja IS 'Tiene teléfono de linea baja';
COMMENT ON COLUMN ficha_hogar.numero_telefono_linea_baja IS 'Número de teléfono de linea baja';
COMMENT ON COLUMN ficha_hogar.numero_siono_disp_heladera IS 'Dispone de heladera en el hogar';
COMMENT ON COLUMN ficha_hogar.numero_siono_disp_lavarropas IS 'Dispone de lavarropas en el hogar';
COMMENT ON COLUMN ficha_hogar.numero_siono_disp_termo IS 'Dispone de termocalefón en el hogar';
COMMENT ON COLUMN ficha_hogar.numero_siono_disp_aire_acon IS 'Dispone de aire acondicionado en el hogar';
COMMENT ON COLUMN ficha_hogar.numero_siono_disp_automovil IS 'Dispone de automóvil ó camioneta en el hogar';
COMMENT ON COLUMN ficha_hogar.numero_siono_disp_camion IS 'Dispone de camión en el hogar';
COMMENT ON COLUMN ficha_hogar.numero_siono_disp_motocicleta IS 'Dispone de motocicleta en el hogar';
COMMENT ON COLUMN ficha_hogar.nombre_jefe_hogar IS 'Nombre del jefe de hogar';
COMMENT ON COLUMN ficha_hogar.numero_cedula_jefe_hogar IS 'Número de cédula del jefe de hogar';
COMMENT ON COLUMN ficha_hogar.letra_cedula_jefe_hogar IS 'Letra de la cédula del jefe de hogar';
COMMENT ON COLUMN ficha_hogar.numero_orden_iden_jefe_hogar IS 'Número de orden de identificación del jefe de hogar';
COMMENT ON COLUMN ficha_hogar.nombre_respondente IS 'Nombre del respondente';
COMMENT ON COLUMN ficha_hogar.numero_cedula_respondente IS 'Número de cédula del respondente';
COMMENT ON COLUMN ficha_hogar.letra_cedula_respondente IS 'Letra de la cédula del respondente';
COMMENT ON COLUMN ficha_hogar.numero_orden_iden_respondente IS 'Número de orden de identificación del respondente';
COMMENT ON TABLE  ficha_persona IS '';
COMMENT ON COLUMN ficha_persona.numero_orden_identificacion IS 'Número de orden de identificación de la persona';
COMMENT ON COLUMN ficha_persona.numero_tipo_persona_hogar IS 'Parentesco familiar con el/la jefe/a del hogar';
COMMENT ON COLUMN ficha_persona.numero_siono_miembro_hogar IS 'Es miembro del hogar';
COMMENT ON COLUMN ficha_persona.numero_orden_iden_conyuge IS 'Número de orden de identificación del conyuge';
COMMENT ON COLUMN ficha_persona.numero_orden_iden_padre IS 'Número de orden de identificación del padre';
COMMENT ON COLUMN ficha_persona.numero_orden_iden_madre IS 'Número de orden de identificación de la madre';
COMMENT ON COLUMN ficha_persona.numero_tipo_excepcion_ced IS 'Razón por la que no se dispone del número de cédula de la persona';
COMMENT ON COLUMN ficha_persona.id_departamento_nacimiento IS 'Departamento donde vivía la madre cuando nació';
COMMENT ON COLUMN ficha_persona.id_distrito_nacimiento IS 'Distrito donde vivía la madre cuando nació';
COMMENT ON COLUMN ficha_persona.numero_tipo_area_lugar_nac IS 'Tipo de área (urbana o rural) donde vivía la madre cuando nació';
COMMENT ON COLUMN ficha_persona.numero_idioma_hogar IS 'Idioma que habla en la casa la mayor parte del tiempo';
COMMENT ON COLUMN ficha_persona.otro_idioma_hogar IS 'Idioma que habla en la casa la mayor parte del tiempo (especificar si la respuesta anterior es 4 "Otro idioma")';
COMMENT ON COLUMN ficha_persona.numero_siono_asistencia_esc IS 'Asiste o asistió a una escuela, colegio o institucion de enseñanza regular';
COMMENT ON COLUMN ficha_persona.numero_motivo_ina_esc IS 'Motivo por el que no asiste o dejó de asistir a la escuela, colegio o institucion de enseñanza regular';
COMMENT ON COLUMN ficha_persona.otro_motivo_ina_esc IS 'Motivo por el que no asiste o dejó de asistir a la escuela, colegio o institucion de enseñanza regular (especificar si la respuesta anterior es 25 "Otros")';
COMMENT ON COLUMN ficha_persona.numero_siono_matriculacion_esc IS 'Esta matriculado actualmente en una institución educativa';
COMMENT ON COLUMN ficha_persona.ultimo_curso_aprobado IS 'Ultimo grado/ciclo o curso que aprobó';
COMMENT ON COLUMN ficha_persona.numero_nivel_edu_ult_cur_aprob IS 'Nivel al que corresponde el último grado/ciclo o curso que aprobó';
COMMENT ON COLUMN ficha_persona.numero_siono_curso_no_formal IS 'Realizó algún curso no formal para poder trabajar, ejercer algún oficio o mejorar su nivel cultural';
COMMENT ON COLUMN ficha_persona.numero_tipo_seguro_medico IS 'Tiene seguro médico vigente en el país';
COMMENT ON COLUMN ficha_persona.numero_estado_salud IS 'Durante los últimos 90 dias, se sintió o estuvo enfermo y/o accidentado';
COMMENT ON COLUMN ficha_persona.numero_clase_enf_acc IS 'Enfermedad y/o accidente que tuvo durante los últimos 90 dias';
COMMENT ON COLUMN ficha_persona.otra_clase_enf_acc IS 'Enfermedad y/o accidente que tuvo durante los últimos 90 dias (especificar si la respuesta anterior es 44 "Otros")';
COMMENT ON COLUMN ficha_persona.numero_clase_enf_cronica IS 'Enfermedad crónica que tiene';
COMMENT ON COLUMN ficha_persona.otra_clase_enf_cronica IS 'Enfermedad crónica que tiene (especificar si la respuesta anterior es 42 "Otros")';
COMMENT ON COLUMN ficha_persona.numero_siono_atencion_medica IS 'Recibió atención médica por la enfermedad y/o accidente que tuvo o tiene';
COMMENT ON COLUMN ficha_persona.numero_motivo_no_atencion IS 'Motivo por el que no recibió atención médica';
COMMENT ON COLUMN ficha_persona.otro_motivo_no_atencion IS 'Motivo por el que no recibió atención médica (especificar si la respuesta anterior es 9 "Otros")';
COMMENT ON COLUMN ficha_persona.numero_siono_carnet_vacunacion IS 'Tiene carnet de vacunación';
COMMENT ON COLUMN ficha_persona.numero_clase_impedimento IS 'Tiene impedimento físico o mental de forma permanente';
COMMENT ON COLUMN ficha_persona.otra_clase_impedimento IS 'Tiene impedimento físico o mental de forma permanente (especificar si la respuesta anterior es 13 "Otros")';
COMMENT ON COLUMN ficha_persona.numero_causa_impedimento IS 'Causa del impedimento';
COMMENT ON COLUMN ficha_persona.otra_causa_impedimento IS 'Causa del impedimento (especificar si la respuesta anterior es 5 "Otros")';
COMMENT ON COLUMN ficha_persona.numero_siono_dif_para_caminar IS 'Tiene dificultad para cruzar una pieza/habitación caminando';
COMMENT ON COLUMN ficha_persona.numero_siono_dif_para_vestirse IS 'Tiene dificultad para vestirse, incluyendo ponerse los zapatos y las medias';
COMMENT ON COLUMN ficha_persona.numero_siono_dif_para_banarse IS 'Tiene dificultad para bañarse, incluyendo entrar y salid de la bañadera';
COMMENT ON COLUMN ficha_persona.numero_siono_dif_para_comer IS 'Tiene dificultad para comer, incluyendo cortar la comida, llenar los vasos, etc.';
COMMENT ON COLUMN ficha_persona.numero_siono_dif_para_la_cama IS 'Tiene dificultad para acostarse o pararse de la cama';
COMMENT ON COLUMN ficha_persona.numero_siono_dif_para_el_bano IS 'Tiene dificultad para usar el servicio sanitario, incluyendo sentarse o levantarse del excusado o inodoro';
COMMENT ON COLUMN ficha_persona.numero_siono_trabajo IS 'Durante los últimos 30 dias trabajó, realizó alguna changa, o hizo algún producto dentro o fuera de su casa para vender, o prestó algún servicio, o ayudó a alguien en su trabajo, negocio o chacra';
COMMENT ON COLUMN ficha_persona.numero_motivo_no_trabajo IS 'Motivo principal por el que no trabajó durante los últimos 30 dias';
COMMENT ON COLUMN ficha_persona.otro_motivo_no_trabajo IS 'Motivo principal por el que no trabajó durante los últimos 30 dias (especificar si la respuesta anterior es 9 "Otros")';
COMMENT ON COLUMN ficha_persona.descripcion_ocupacion_prin IS 'Ocupación principal en el trabajo que realiza o realizaba';
COMMENT ON COLUMN ficha_persona.descripcion_dedicacion_prin IS 'Producto o servicio principal que se produce o se presta en el lugar donde trabaja o trabajaba';
COMMENT ON COLUMN ficha_persona.numero_tipo_relacion_lab IS 'Relación laboral que mentiene o mantenía';
COMMENT ON COLUMN ficha_persona.monto_ingreso_ocupacion_prin IS 'Monto del ingreso mensual que habitualmente recibe en su ocupación principal';
COMMENT ON COLUMN ficha_persona.monto_ingreso_ocupacion_secun IS 'Monto del ingreso mensual que habitualmente recibe en su ocupación secundaria';
COMMENT ON COLUMN ficha_persona.monto_ingreso_otras_ocup IS 'Monto del ingreso mensual que habitualmente recibe en todas las otras ocupaciones';
COMMENT ON COLUMN ficha_persona.monto_ingreso_alquileres IS 'Monto del ingreso mensual que habitualmente recibe por alquileres o rentas (neto)';
COMMENT ON COLUMN ficha_persona.monto_ingreso_intereses IS 'Monto del ingreso mensual que habitualmente recibe por intereses, dividendos o utilidades';
COMMENT ON COLUMN ficha_persona.monto_ingreso_ayuda_fam_pais IS 'Monto del ingreso mensual que habitualmente recibe por ayuda familiar del país';
COMMENT ON COLUMN ficha_persona.monto_ingreso_ayuda_fam_exter IS 'Monto del ingreso mensual que habitualmente recibe por ayuda familiar del exterior';
COMMENT ON COLUMN ficha_persona.monto_ingreso_jubilacion IS 'Monto del ingreso mensual que habitualmente recibe por jubilación o pensión';
COMMENT ON COLUMN ficha_persona.monto_ingreso_pensiones IS 'Monto del ingreso mensual que habitualmente recibe por pensiones o prestaciones por divorcios o cuidados de hijos';
COMMENT ON COLUMN ficha_persona.monto_ingreso_tekopora IS 'Monto del ingreso mensual que habitualmente recibe por Tekopora';
COMMENT ON COLUMN ficha_persona.monto_ingreso_programas IS 'Monto del ingreso mensual que habitualmente recibe por otros programas';
COMMENT ON COLUMN ficha_persona.monto_ingreso_adicional IS 'Monto del ingreso mensual que habitualmente recibe por otras fuentes';
COMMENT ON COLUMN ficha_persona.total_ingreso_mensual IS 'Monto total del ingreso mensual que habitualmente recibe por cualquier fuente (suma de todos los montos anteriores)';
COMMENT ON TABLE  log_imp_deu IS '';
COMMENT ON COLUMN log_imp_deu.referencia IS 'Número de NIS (Si aplica)';
COMMENT ON TABLE  log_imp_hog IS '';
COMMENT ON COLUMN log_imp_hog.p20d IS 'Día de la entrevista';
COMMENT ON COLUMN log_imp_hog.p20m IS 'Mes de la entrevista';
COMMENT ON COLUMN log_imp_hog.p20a IS 'Año de la entrevista';
COMMENT ON COLUMN log_imp_hog.p17 IS 'Funcionario censista';
COMMENT ON COLUMN log_imp_hog.p18 IS 'Funcionario cupervisor';
COMMENT ON COLUMN log_imp_hog.var00001 IS 'Funcionario crítico decodificador';
COMMENT ON COLUMN log_imp_hog.p19 IS 'Funcionario Digitador';
COMMENT ON COLUMN log_imp_hog.observaciones IS 'Observaciones de Campo';
COMMENT ON COLUMN log_imp_hog.utm IS 'Número de Zona ó Huso de la ubicación de la vivienda (según GPS)';
COMMENT ON COLUMN log_imp_hog.gps IS 'Banda ó Franja de la ubicación de la vivienda (según GPS)  ';
COMMENT ON COLUMN log_imp_hog.orden IS 'Distancia vertical al Norte de la ubicación de la vivienda (según GPS) ';
COMMENT ON COLUMN log_imp_hog.coordx IS 'Distancia horizontal al Este de la ubicación de la vivienda (según GPS)';
COMMENT ON COLUMN log_imp_hog.p01a IS 'Código Departamento';
COMMENT ON COLUMN log_imp_hog.p01b IS 'Código Distrito';
COMMENT ON COLUMN log_imp_hog.p01c IS 'Código Barrio';
COMMENT ON COLUMN log_imp_hog.p01d IS 'Número Formulario';
COMMENT ON COLUMN log_imp_hog.p02 IS 'Número Vivienda';
COMMENT ON COLUMN log_imp_hog.p03 IS 'Número Hogar';
COMMENT ON COLUMN log_imp_hog.p04 IS 'Nombre Departamento';
COMMENT ON COLUMN log_imp_hog.p05 IS 'Nombre Distrito';
COMMENT ON COLUMN log_imp_hog.p06 IS 'Tipo de Área';
COMMENT ON COLUMN log_imp_hog.p08 IS 'Nombre de Barrio';
COMMENT ON COLUMN log_imp_hog.p07 IS 'Nombre de Manzana';
COMMENT ON COLUMN log_imp_hog.p09 IS 'Dirección de la vivienda';
COMMENT ON COLUMN log_imp_hog.p14 IS 'Total de personas que viven en el hogar';
COMMENT ON COLUMN log_imp_hog.p15 IS 'Total de hombres que viven en el hogar';
COMMENT ON COLUMN log_imp_hog.p16 IS 'Total de mujeres que viven el hogar';
COMMENT ON COLUMN log_imp_hog.p24 IS 'Material predominante en las paredes exteriores';
COMMENT ON COLUMN log_imp_hog.p25 IS 'Material predominante en el piso ';
COMMENT ON COLUMN log_imp_hog.p26 IS 'Material predominante en el techo';
COMMENT ON COLUMN log_imp_hog.p27 IS 'Condición de ocupación de la vivienda';
COMMENT ON COLUMN log_imp_hog.p27e IS 'Otra condición de ocupación de la vivienda';
COMMENT ON COLUMN log_imp_hog.p28a IS 'Número de piezas de la vivienda';
COMMENT ON COLUMN log_imp_hog.p28b IS 'Número de dormitorios de la vivienda';
COMMENT ON COLUMN log_imp_hog.p29 IS 'Tiene pieza para cocinar ';
COMMENT ON COLUMN log_imp_hog.p30 IS 'Combustible que se utiliza en forma habitual para cocinar  ';
COMMENT ON COLUMN log_imp_hog.p31 IS 'Tipo de pieza para bañarse';
COMMENT ON COLUMN log_imp_hog.p32 IS 'Tipo de desagüe que tiene el baño ';
COMMENT ON COLUMN log_imp_hog.p33 IS 'Procedencia del agua que se utiliza en l a vivienda  ';
COMMENT ON COLUMN log_imp_hog.p34 IS 'Lugar de abastecimiento del agua que se utiliza en l a vivienda  ';
COMMENT ON COLUMN log_imp_hog.p35 IS 'Dispone de luz eléctrica';
COMMENT ON COLUMN log_imp_hog.p36 IS 'Forma de desechar la basura ';
COMMENT ON COLUMN log_imp_hog.p37 IS 'Tiene teléfono celular  ';
COMMENT ON COLUMN log_imp_hog.nro_celular IS 'Número de teléfono celular';
COMMENT ON COLUMN log_imp_hog.p38 IS 'Tiene teléfono línea baja';
COMMENT ON COLUMN log_imp_hog.nro_linea_baja IS 'Número de teléfono línea baja';
COMMENT ON COLUMN log_imp_hog.p391 IS 'Dispone de heladera en el hogar';
COMMENT ON COLUMN log_imp_hog.p392 IS 'Dispone de lavarropas en el hogar ';
COMMENT ON COLUMN log_imp_hog.p393 IS 'Dispone de termocalefón en el hogar ';
COMMENT ON COLUMN log_imp_hog.p394 IS 'Dispone de aire acondicionado en el hogar ';
COMMENT ON COLUMN log_imp_hog.p395 IS 'Dispone de automóvil o camioneta en el hogar ';
COMMENT ON COLUMN log_imp_hog.p396 IS 'Dispone de camión en el hogar ';
COMMENT ON COLUMN log_imp_hog.p397 IS 'Dispone de motocicleta en el hogar ';
COMMENT ON COLUMN log_imp_hog.p42n IS 'Nombre del jefe del hogar';
COMMENT ON COLUMN log_imp_hog.p42ci IS 'Número de cédula del jefe del hogar';
COMMENT ON COLUMN log_imp_hog.letra_ci IS 'Letra de cédula del jefe del hogar';
COMMENT ON COLUMN log_imp_hog.p43 IS 'Orden del jefe del hogar';
COMMENT ON COLUMN log_imp_hog.var00002 IS 'Nombre del respondente';
COMMENT ON COLUMN log_imp_hog.var00003 IS 'Número de cédula del respondente';
COMMENT ON COLUMN log_imp_hog.var00004 IS 'Letra de cédula del respondente';
COMMENT ON COLUMN log_imp_hog.p104 IS 'Orden del respondente';
COMMENT ON TABLE  log_imp_hog_eec IS '';
COMMENT ON COLUMN log_imp_hog_eec.dptod IS 'Código de departamento';
COMMENT ON COLUMN log_imp_hog_eec.distritod IS 'Código de distrito';
COMMENT ON COLUMN log_imp_hog_eec.distripg IS 'Código de departamento+distrito';
COMMENT ON COLUMN log_imp_hog_eec.area IS 'Tipo de area';
COMMENT ON COLUMN log_imp_hog_eec.barrio IS 'Código del barrio';
COMMENT ON COLUMN log_imp_hog_eec.manzana IS 'Nombre de la manzana';
COMMENT ON COLUMN log_imp_hog_eec.formulario IS 'Número de formulario';
COMMENT ON COLUMN log_imp_hog_eec.vivi IS 'Número de vivienda';
COMMENT ON COLUMN log_imp_hog_eec.hogar IS 'Número de hogar';
COMMENT ON COLUMN log_imp_hog_eec.direccion IS 'Dirección de la vivienda';
COMMENT ON COLUMN log_imp_hog_eec.nro_de IS 'Número de la casa';
COMMENT ON COLUMN log_imp_hog_eec.telefono IS 'Número de teléfono';
COMMENT ON COLUMN log_imp_hog_eec.fecha IS 'Fecha de la entrevista';
COMMENT ON COLUMN log_imp_hog_eec.dia IS 'Día de la entrevista';
COMMENT ON COLUMN log_imp_hog_eec.mes IS 'Mes de la entrevista';
COMMENT ON COLUMN log_imp_hog_eec.ano IS 'Año de la entrevista';
COMMENT ON COLUMN log_imp_hog_eec.v10t IS 'Total de personas que viven en el hogar';
COMMENT ON COLUMN log_imp_hog_eec.v11 IS 'Total de hombres que viven en el hogar';
COMMENT ON COLUMN log_imp_hog_eec.v12 IS 'Total de mujeres que viven el hogar';
COMMENT ON COLUMN log_imp_hog_eec.v13 IS 'Material predominante en las paredes exteriores';
COMMENT ON COLUMN log_imp_hog_eec.v14 IS 'Material predominante en el piso ';
COMMENT ON COLUMN log_imp_hog_eec.v15 IS 'Material predominante en el techo';
COMMENT ON COLUMN log_imp_hog_eec.v16 IS 'Condición de ocupación de la vivienda';
COMMENT ON COLUMN log_imp_hog_eec.v16_otr IS 'Otra condición de ocupación de la vivienda';
COMMENT ON COLUMN log_imp_hog_eec.v17a IS 'Número de piezas de la vivienda';
COMMENT ON COLUMN log_imp_hog_eec.v17b IS 'Número de dormitorios de la vivienda';
COMMENT ON COLUMN log_imp_hog_eec.v18 IS 'Tiene pieza para cocinar ';
COMMENT ON COLUMN log_imp_hog_eec.v19 IS 'Combustible que se utiliza en forma habitual para cocinar  ';
COMMENT ON COLUMN log_imp_hog_eec.v20 IS 'Tipo de pieza para bañarse';
COMMENT ON COLUMN log_imp_hog_eec.v21 IS 'Tipo de desagüe que tiene el baño ';
COMMENT ON COLUMN log_imp_hog_eec.v22 IS 'Procedencia del agua que se utiliza en l a vivienda  ';
COMMENT ON COLUMN log_imp_hog_eec.v23 IS 'Lugar de abastecimiento del agua que se utiliza en l a vivienda  ';
COMMENT ON COLUMN log_imp_hog_eec.v24 IS 'Dispone de luz eléctrica';
COMMENT ON COLUMN log_imp_hog_eec.v25 IS 'Forma de desechar la basura ';
COMMENT ON COLUMN log_imp_hog_eec.v26 IS 'Tiene teléfono celular  ';
COMMENT ON COLUMN log_imp_hog_eec.v26esp_celular IS 'Número de teléfono celular';
COMMENT ON COLUMN log_imp_hog_eec.v27 IS 'Tiene teléfono línea baja';
COMMENT ON COLUMN log_imp_hog_eec.v27esp_linea IS 'Número de teléfono línea baja';
COMMENT ON COLUMN log_imp_hog_eec.v28_1 IS 'Dispone de heladera en el hogar';
COMMENT ON COLUMN log_imp_hog_eec.v28_2 IS 'Dispone de lavarropas en el hogar ';
COMMENT ON COLUMN log_imp_hog_eec.v28_3 IS 'Dispone de termocalefón en el hogar ';
COMMENT ON COLUMN log_imp_hog_eec.v28_4 IS 'Dispone de aire acondicionado en el hogar ';
COMMENT ON COLUMN log_imp_hog_eec.v28_5 IS 'Dispone de automóvil o camioneta en el hogar ';
COMMENT ON COLUMN log_imp_hog_eec.v28_6 IS 'Dispone de camión en el hogar ';
COMMENT ON COLUMN log_imp_hog_eec.v28_7 IS 'Dispone de motocicleta en el hogar ';
COMMENT ON COLUMN log_imp_hog_eec.v28_8 IS 'No dispone de ninguno de los otros bienes';
COMMENT ON COLUMN log_imp_hog_eec.v29nombre_jefe IS 'Nombre del jefe del hogar';
COMMENT ON COLUMN log_imp_hog_eec.cedulajefe IS 'Número de cédula del jefe del hogar';
COMMENT ON COLUMN log_imp_hog_eec.var00001 IS 'Número de ficha persona';
COMMENT ON TABLE  log_imp_per IS '';
COMMENT ON COLUMN log_imp_per.p01a IS 'Código del departamento';
COMMENT ON COLUMN log_imp_per.p01b IS 'Código del distrito';
COMMENT ON COLUMN log_imp_per.p01c IS 'Código del barrio';
COMMENT ON COLUMN log_imp_per.p01d IS 'Número de formulario';
COMMENT ON COLUMN log_imp_per.p02 IS 'Número de vivienda';
COMMENT ON COLUMN log_imp_per.p03 IS 'Número de hogar';
COMMENT ON COLUMN log_imp_per.p104 IS 'Orden del respondente';
COMMENT ON COLUMN log_imp_per.p43 IS 'Orden de la persona censada';
COMMENT ON COLUMN log_imp_per.p45a IS 'Primer nombre de la persona';
COMMENT ON COLUMN log_imp_per.p45b IS 'Segundo nombre de la persona';
COMMENT ON COLUMN log_imp_per.p44a IS 'Primer apellido de la persona';
COMMENT ON COLUMN log_imp_per.p44b IS 'Segundo apellido de la persona';
COMMENT ON COLUMN log_imp_per.var00001 IS 'Apellido de casada de la persona';
COMMENT ON COLUMN log_imp_per.var00002 IS 'Apodo de la persona';
COMMENT ON COLUMN log_imp_per.p46 IS 'Edad de la persona';
COMMENT ON COLUMN log_imp_per.p47 IS 'Sexo de la persona';
COMMENT ON COLUMN log_imp_per.var00030 IS 'Estado civil de la persona';
COMMENT ON COLUMN log_imp_per.p48 IS 'Parentesco de la persona con el jefe del hogar';
COMMENT ON COLUMN log_imp_per.p49 IS 'Es la persona miembro del hogar';
COMMENT ON COLUMN log_imp_per.p50a IS 'Orden del cónyuge de la persona';
COMMENT ON COLUMN log_imp_per.p50b IS 'Orden del padre de la persona';
COMMENT ON COLUMN log_imp_per.p50c IS 'Orden de la madre de la persona';
COMMENT ON COLUMN log_imp_per.p51 IS 'Número de cédula de la persona';
COMMENT ON COLUMN log_imp_per.var00003 IS 'Letra de la cédula de la persona';
COMMENT ON COLUMN log_imp_per.var00004 IS 'Tipo de excepción de cédula de identidad de la persona';
COMMENT ON COLUMN log_imp_per.p52d IS 'Día de nacimiento de la persona';
COMMENT ON COLUMN log_imp_per.p52m IS 'Mes de nacimiento de la persona';
COMMENT ON COLUMN log_imp_per.p52a IS 'Año de nacimiento de la persona';
COMMENT ON COLUMN log_imp_per.p53a IS 'Departamento en que nació la persona';
COMMENT ON COLUMN log_imp_per.p53b IS 'Distrito en que nació la persona';
COMMENT ON COLUMN log_imp_per.p53c IS 'Código del distrito de nacimiento';
COMMENT ON COLUMN log_imp_per.p53z IS 'Tipo de área del lugar de nacimiento';
COMMENT ON COLUMN log_imp_per.p54 IS 'Idioma que habla mayormente';
COMMENT ON COLUMN log_imp_per.p54e IS 'Otro idioma';
COMMENT ON COLUMN log_imp_per.p56 IS 'Asistió a clases el año pasado';
COMMENT ON COLUMN log_imp_per.p58 IS 'Por qué no asistió a clases el año pasado';
COMMENT ON COLUMN log_imp_per.p58e IS 'Otro motivo de no asistencia';
COMMENT ON COLUMN log_imp_per.p59 IS 'Piensa matricularse este año';
COMMENT ON COLUMN log_imp_per.p60 IS 'Último grado o curso aprobado';
COMMENT ON COLUMN log_imp_per.p61 IS 'Nivel del último grado o curso aprobado';
COMMENT ON COLUMN log_imp_per.p62 IS 'Realizó curso no formal';
COMMENT ON COLUMN log_imp_per.p63 IS 'Tiene seguro médico vigente';
COMMENT ON COLUMN log_imp_per.p64 IS 'Estuvo enfermo o accidentado';
COMMENT ON COLUMN log_imp_per.p65 IS 'Que enfermedad tuvo';
COMMENT ON COLUMN log_imp_per.p65e IS 'Otra enfermedad';
COMMENT ON COLUMN log_imp_per.p66 IS 'Qué enfermedad crónica padece';
COMMENT ON COLUMN log_imp_per.p66e IS 'Otra enfermedad crónica';
COMMENT ON COLUMN log_imp_per.p67 IS 'Recibió atención por la enfermedad o accidente';
COMMENT ON COLUMN log_imp_per.p68 IS 'Por qué no recibió atención';
COMMENT ON COLUMN log_imp_per.p68e IS 'Otro motivo de no atención';
COMMENT ON COLUMN log_imp_per.p73 IS 'Tiene carné de vacunación';
COMMENT ON COLUMN log_imp_per.p74 IS 'Clase de impedimento físico';
COMMENT ON COLUMN log_imp_per.var00006 IS 'Otra clase de impedimento físico';
COMMENT ON COLUMN log_imp_per.var00007 IS 'Número de causa de impedimento físico';
COMMENT ON COLUMN log_imp_per.var00008 IS 'Otra causa de impedimento físico';
COMMENT ON COLUMN log_imp_per.var00009 IS 'Tiene dificultad para caminar';
COMMENT ON COLUMN log_imp_per.var00010 IS 'Tiene dificultad para vestirse';
COMMENT ON COLUMN log_imp_per.var00011 IS 'Tiene dificultad para bañarse';
COMMENT ON COLUMN log_imp_per.var00031 IS 'Tiene dificultad para comer';
COMMENT ON COLUMN log_imp_per.var00012 IS 'Tiene dificultad para ir a la cama';
COMMENT ON COLUMN log_imp_per.var00013 IS 'Tiene dificultad para ir al baño';
COMMENT ON COLUMN log_imp_per.p86 IS 'Realizó alguna actividad económica';
COMMENT ON COLUMN log_imp_per.p87 IS 'Razón por la que no trabajó';
COMMENT ON COLUMN log_imp_per.p87e IS 'Otra razón por la que no trabajó';
COMMENT ON COLUMN log_imp_per.p88 IS 'Ocupación principal';
COMMENT ON COLUMN log_imp_per.p88e IS 'Otra ocupación principal';
COMMENT ON COLUMN log_imp_per.p91 IS 'Tipo Relación laboral';
COMMENT ON COLUMN log_imp_per.var00017 IS 'Monto de ingreso por ocupación principal';
COMMENT ON COLUMN log_imp_per.var00018 IS 'Monto de ingreso por ocupacion secundaria';
COMMENT ON COLUMN log_imp_per.var00019 IS 'Monto  de ingreso por otras ocupaciones';
COMMENT ON COLUMN log_imp_per.var00020 IS 'Monto de ingreso por alquileres';
COMMENT ON COLUMN log_imp_per.var00021 IS 'Monto de ingreso por intereses';
COMMENT ON COLUMN log_imp_per.var00022 IS 'Monto de ingreso por ayuda familiar dentro del país';
COMMENT ON COLUMN log_imp_per.var00023 IS 'Monto de ingreso por ayuda familiar del exterior';
COMMENT ON COLUMN log_imp_per.var00024 IS 'Monto de ingreso por jubilacion';
COMMENT ON COLUMN log_imp_per.var00025 IS 'Monto de ingreso por pensiones';
COMMENT ON COLUMN log_imp_per.var00026 IS 'Monto de ingreso por tekopora';
COMMENT ON COLUMN log_imp_per.var00027 IS 'Monto de ingreso por otros programas';
COMMENT ON COLUMN log_imp_per.var00028 IS 'Monto de ingreso adicional';
COMMENT ON COLUMN log_imp_per.p92 IS 'Ingreso total mensual';
COMMENT ON COLUMN log_imp_per.icv IS 'Indice Calidad Vida';
COMMENT ON COLUMN log_imp_per.ficha_activa IS 'Ficha Activa';
COMMENT ON TABLE  log_imp_per_eec IS '';
COMMENT ON COLUMN log_imp_per_eec.dptod IS 'Código de departamento';
COMMENT ON COLUMN log_imp_per_eec.distritod IS 'Código de distrito';
COMMENT ON COLUMN log_imp_per_eec.distripg IS 'Código de departamento+distrito';
COMMENT ON COLUMN log_imp_per_eec.area IS 'Tipo de area';
COMMENT ON COLUMN log_imp_per_eec.barrio IS 'Código del barrio';
COMMENT ON COLUMN log_imp_per_eec.manzana IS 'Nombre de la manzana';
COMMENT ON COLUMN log_imp_per_eec.formulario IS 'Número de formulario';
COMMENT ON COLUMN log_imp_per_eec.vivi IS 'Número de vivienda';
COMMENT ON COLUMN log_imp_per_eec.hogar IS 'Número de hogar';
COMMENT ON COLUMN log_imp_per_eec.orden IS 'Orden del respondente';
COMMENT ON COLUMN log_imp_per_eec.p30 IS 'Nombres de la persona';
COMMENT ON COLUMN log_imp_per_eec.p31 IS 'Apellidos de la persona';
COMMENT ON COLUMN log_imp_per_eec.p32 IS 'Edad de la persona';
COMMENT ON COLUMN log_imp_per_eec.p33 IS 'Sexo de la persona';
COMMENT ON COLUMN log_imp_per_eec.p34 IS 'Parentesco de la persona con el jefe del hogar';
COMMENT ON COLUMN log_imp_per_eec.p35 IS 'Es la persona miembro del hogar';
COMMENT ON COLUMN log_imp_per_eec.p36_orden_conyugue IS 'Orden del cónyuge de la persona';
COMMENT ON COLUMN log_imp_per_eec.p36_orden_padre IS 'Orden del padre de la persona';
COMMENT ON COLUMN log_imp_per_eec.p36_orden_madre IS 'Orden de la madre de la persona';
COMMENT ON COLUMN log_imp_per_eec.p37 IS 'N° control';
COMMENT ON COLUMN log_imp_per_eec.p37_cedula IS 'Número de cédula de la persona';
COMMENT ON COLUMN log_imp_per_eec.p38_dia IS 'Día de nacimiento de la persona';
COMMENT ON COLUMN log_imp_per_eec.p38_mes IS 'Mes de nacimiento de la persona';
COMMENT ON COLUMN log_imp_per_eec.p38_ano IS 'Año de nacimiento de la persona';
COMMENT ON COLUMN log_imp_per_eec.p39pais IS 'País de nacimiento de la persona';
COMMENT ON COLUMN log_imp_per_eec.p39dpto IS 'Código de departamento';
COMMENT ON COLUMN log_imp_per_eec.p39dist IS 'Código de distrito';
COMMENT ON COLUMN log_imp_per_eec.p39area IS 'Tipo de área del lugar de nacimiento';
COMMENT ON COLUMN log_imp_per_eec.p40_idioma IS 'Idioma que habla mayormente';
COMMENT ON COLUMN log_imp_per_eec.p40otr IS 'Otro idioma';
COMMENT ON COLUMN log_imp_per_eec.p41 IS 'Asistió a clases el año pasado';
COMMENT ON COLUMN log_imp_per_eec.p42 IS 'Por qué no asistió a clases el año pasado';
COMMENT ON COLUMN log_imp_per_eec.p43 IS 'Está matriculado actualmente en una Institución Educativa';
COMMENT ON COLUMN log_imp_per_eec.p44_45t IS 'Grado+nivel último curso aprobado';
COMMENT ON COLUMN log_imp_per_eec.p44 IS 'Último grado o curso aprobado';
COMMENT ON COLUMN log_imp_per_eec.p45 IS 'Nivel del último grado o curso aprobado';
COMMENT ON COLUMN log_imp_per_eec.p46 IS 'Realizó curso no formal';
COMMENT ON COLUMN log_imp_per_eec.p47 IS 'Tiene seguro médico vigente';
COMMENT ON COLUMN log_imp_per_eec.p48 IS 'Estuvo enfermo o accidentado';
COMMENT ON COLUMN log_imp_per_eec.p49 IS 'Que enfermedad tuvo';
COMMENT ON COLUMN log_imp_per_eec.p49_otr IS 'Otra enfermedad';
COMMENT ON COLUMN log_imp_per_eec.p50 IS 'Qué enfermedad crónica padece';
COMMENT ON COLUMN log_imp_per_eec.p50_otr IS 'Otra enfermedad crónica';
COMMENT ON COLUMN log_imp_per_eec.p51 IS 'Recibió atención por la enfermedad o accidente';
COMMENT ON COLUMN log_imp_per_eec.p52 IS 'Por qué no recibió atención';
COMMENT ON COLUMN log_imp_per_eec.p52_otr IS 'Otro motivo de no atención';
COMMENT ON COLUMN log_imp_per_eec.p53 IS 'Tiene carné de vacunación';
COMMENT ON COLUMN log_imp_per_eec.p54 IS 'Tiene impedimento físico de forma permanente';
COMMENT ON COLUMN log_imp_per_eec.p54a IS 'Impedimento físico permanente';
COMMENT ON COLUMN log_imp_per_eec.p54_otr IS 'Otra clase de impedimento físico';
COMMENT ON COLUMN log_imp_per_eec.p55 IS 'Número de causa de impedimento físico';
COMMENT ON COLUMN log_imp_per_eec.p55_otr IS 'Otra causa de impedimento físico';
COMMENT ON COLUMN log_imp_per_eec.p56 IS 'Tiene dificultad para caminar';
COMMENT ON COLUMN log_imp_per_eec.p57 IS 'Tiene dificultad para vestirse';
COMMENT ON COLUMN log_imp_per_eec.p58 IS 'Tiene dificultad para bañarse';
COMMENT ON COLUMN log_imp_per_eec.p59 IS 'Tiene dificultad para comer';
COMMENT ON COLUMN log_imp_per_eec.p60 IS 'Tiene dificultad para ir a la cama';
COMMENT ON COLUMN log_imp_per_eec.p61 IS 'Tiene dificultad para ir al baño';
COMMENT ON COLUMN log_imp_per_eec.p62 IS 'Realizó alguna actividad económica';
COMMENT ON COLUMN log_imp_per_eec.p63 IS 'Razón por la que no trabajó';
COMMENT ON COLUMN log_imp_per_eec.p63_especificar IS 'Otra razón por la que no trabajó';
COMMENT ON COLUMN log_imp_per_eec.p64des IS 'Ocupación principal';
COMMENT ON COLUMN log_imp_per_eec.p64c IS 'Código de ocupación principal';
COMMENT ON COLUMN log_imp_per_eec.p65des IS 'Negocio lugar de trabajo';
COMMENT ON COLUMN log_imp_per_eec.p65c IS 'Código de rama de actividades';
COMMENT ON COLUMN log_imp_per_eec.p66 IS 'Tipo Relación laboral';
COMMENT ON COLUMN log_imp_per_eec.p67a IS 'Monto de ingreso por ocupación principal';
COMMENT ON COLUMN log_imp_per_eec.p67b IS 'Monto de ingreso por ocupacion secundaria';
COMMENT ON COLUMN log_imp_per_eec.p67c IS 'Monto  de ingreso por otras ocupaciones';
COMMENT ON COLUMN log_imp_per_eec.p67d IS 'Monto de ingreso por alquileres';
COMMENT ON COLUMN log_imp_per_eec.p67e IS 'Monto de ingreso por intereses';
COMMENT ON COLUMN log_imp_per_eec.p67f IS 'Monto de ingreso por ayuda familiar dentro del país';
COMMENT ON COLUMN log_imp_per_eec.p67g IS 'Monto de ingreso por ayuda familiar del exterior';
COMMENT ON COLUMN log_imp_per_eec.p67h IS 'Monto de ingreso por jubilacion';
COMMENT ON COLUMN log_imp_per_eec.p67i IS 'Monto de ingreso por pensiones';
COMMENT ON COLUMN log_imp_per_eec.p67j IS 'Monto de ingreso por tekopora';
COMMENT ON COLUMN log_imp_per_eec.p67k IS 'Monto de ingreso por otros programas';
COMMENT ON COLUMN log_imp_per_eec.p67l IS 'Monto de ingreso adicional';
COMMENT ON COLUMN log_imp_per_eec.p67tot IS 'Ingreso total mensual';
COMMENT ON TABLE  nivel_educativo IS '';
COMMENT ON COLUMN nivel_educativo.primer_curso IS 'Número del primer curso del nivel';
COMMENT ON COLUMN nivel_educativo.ultimo_curso IS 'Número del último curso del nivel';
COMMENT ON TABLE  objecion_ele_pen IS '';
COMMENT ON COLUMN objecion_ele_pen.fecha_anulacion IS 'Fecha de anulación de la objeción';
COMMENT ON COLUMN objecion_ele_pen.observaciones_anulacion IS 'Motivo por el cual se anula la objeción';
COMMENT ON TABLE  persona IS '';
COMMENT ON COLUMN persona.otra_causa_den_pension IS 'Especificar si la respuesta anterior es 99 "Otra causa"';
COMMENT ON COLUMN persona.otra_causa_rev_pension IS 'Especificar si la respuesta anterior es 99 "Otra causa"';
COMMENT ON COLUMN persona.otra_causa_den_reco_pen IS 'Especificar si la respuesta anterior es 99 "Otra causa"';
COMMENT ON TABLE  potencial_ben IS '';
COMMENT ON COLUMN potencial_ben.es_persona_con_empleo IS 'tiene empleo';
COMMENT ON COLUMN potencial_ben.es_persona_con_jubilacion IS 'tiene jubilación';
COMMENT ON COLUMN potencial_ben.es_persona_con_pension IS 'tiene pensión';
COMMENT ON COLUMN potencial_ben.es_persona_con_subsidio IS 'tiene algún subsidio del Estado';
COMMENT ON COLUMN potencial_ben.es_persona_con_deuda IS 'tiene deudas con el Estado';
COMMENT ON COLUMN potencial_ben.es_persona_con_pena_judicial IS 'tiene pena judicial pendiente';
COMMENT ON COLUMN potencial_ben.es_persona_con_cer_vida IS 'presentó Certificado de Vida y Residencia';
COMMENT ON COLUMN potencial_ben.es_persona_con_carta_renuncia IS 'está dispuesto a firmar la Carta de Renuncia a otras pensiones y/o subsidios';
COMMENT ON COLUMN potencial_ben.otra_causa_inv_censo IS 'Especificar si la respuesta anterior es 99 "Otra causa"';
COMMENT ON COLUMN potencial_ben.otra_causa_den_recl_cen IS 'Especificar si la respuesta anterior es 99 "Otra causa"';
