ALTER TABLE aplicacion DROP (CONSTRAINT UQ_aplicacion_001___);
DROP INDEX aplicacion.UQ_aplicacion_001___;
ALTER TABLE archivo_datos_ext DROP (CONSTRAINT UQ_archivo_datos_ext_001___);
DROP INDEX archivo_datos_ext.UQ_archivo_datos_ext_001___;
ALTER TABLE causa_den_pension DROP (CONSTRAINT UQ_causa_den_pension_001___);
DROP INDEX causa_den_pension.UQ_causa_den_pension_001___;
ALTER TABLE causa_den_recl_cen DROP (CONSTRAINT UQ_causa_den_recl_cen_001___);
DROP INDEX causa_den_recl_cen.UQ_causa_den_recl_cen_001___;
ALTER TABLE causa_den_reco_pen DROP (CONSTRAINT UQ_causa_den_reco_pen_001___);
DROP INDEX causa_den_reco_pen.UQ_causa_den_reco_pen_001___;
ALTER TABLE causa_impedimento DROP (CONSTRAINT UQ_causa_impedimento_001___);
DROP INDEX causa_impedimento.UQ_causa_impedimento_001___;
ALTER TABLE causa_inv_censo DROP (CONSTRAINT UQ_causa_inv_censo_001___);
DROP INDEX causa_inv_censo.UQ_causa_inv_censo_001___;
ALTER TABLE causa_rev_pension DROP (CONSTRAINT UQ_causa_rev_pension_001___);
DROP INDEX causa_rev_pension.UQ_causa_rev_pension_001___;
ALTER TABLE clase_enf_acc DROP (CONSTRAINT UQ_clase_enf_acc_001___);
DROP INDEX clase_enf_acc.UQ_clase_enf_acc_001___;
ALTER TABLE clase_enf_cronica DROP (CONSTRAINT UQ_clase_enf_cronica_001___);
DROP INDEX clase_enf_cronica.UQ_clase_enf_cronica_001___;
ALTER TABLE clase_impedimento DROP (CONSTRAINT UQ_clase_impedimento_001___);
DROP INDEX clase_impedimento.UQ_clase_impedimento_001___;
ALTER TABLE clase_recurso DROP (CONSTRAINT UQ_clase_recurso_001___);
DROP INDEX clase_recurso.UQ_clase_recurso_001___;
ALTER TABLE clase_recurso_par DROP (CONSTRAINT UQ_clase_recurso_par_001___);
DROP INDEX clase_recurso_par.UQ_clase_recurso_par_001___;
ALTER TABLE clase_recurso_sec DROP (CONSTRAINT UQ_clase_recurso_sec_001___);
DROP INDEX clase_recurso_sec.UQ_clase_recurso_sec_001___;
ALTER TABLE condicion_censo DROP (CONSTRAINT UQ_condicion_censo_001___);
DROP INDEX condicion_censo.UQ_condicion_censo_001___;
ALTER TABLE condicion_denu_pen DROP (CONSTRAINT UQ_condicion_denu_pen_001___);
DROP INDEX condicion_denu_pen.UQ_condicion_denu_pen_001___;
ALTER TABLE condicion_eje_fun DROP (CONSTRAINT UQ_condicion_eje_fun_001___);
DROP INDEX condicion_eje_fun.UQ_condicion_eje_fun_001___;
ALTER TABLE condicion_pension DROP (CONSTRAINT UQ_condicion_pension_001___);
DROP INDEX condicion_pension.UQ_condicion_pension_001___;
ALTER TABLE condicion_recl_cen DROP (CONSTRAINT UQ_condicion_recl_cen_001___);
DROP INDEX condicion_recl_cen.UQ_condicion_recl_cen_001___;
ALTER TABLE condicion_reco_pen DROP (CONSTRAINT UQ_condicion_reco_pen_001___);
DROP INDEX condicion_reco_pen.UQ_condicion_reco_pen_001___;
ALTER TABLE conjunto_segmento DROP (CONSTRAINT UQ_conjunto_segmento_001___);
DROP INDEX conjunto_segmento.UQ_conjunto_segmento_001___;
ALTER TABLE dominio DROP (CONSTRAINT UQ_dominio_001___);
DROP INDEX dominio.UQ_dominio_001___;
ALTER TABLE dominio_paquete DROP (CONSTRAINT UQ_dominio_paquete_001___);
DROP INDEX dominio_paquete.UQ_dominio_paquete_001___;
ALTER TABLE dominio_parametro DROP (CONSTRAINT UQ_dominio_parametro_001___);
DROP INDEX dominio_parametro.UQ_dominio_parametro_001___;
ALTER TABLE elemento_segmento DROP (CONSTRAINT UQ_elemento_segmento_001___);
DROP INDEX elemento_segmento.UQ_elemento_segmento_001___;
ALTER TABLE estado_civil DROP (CONSTRAINT UQ_estado_civil_001___);
DROP INDEX estado_civil.UQ_estado_civil_001___;
ALTER TABLE estado_salud DROP (CONSTRAINT UQ_estado_salud_001___);
DROP INDEX estado_salud.UQ_estado_salud_001___;
ALTER TABLE etnia_indigena DROP (CONSTRAINT UQ_etnia_indigena_001___);
DROP INDEX etnia_indigena.UQ_etnia_indigena_001___;
ALTER TABLE ficha_hogar DROP (CONSTRAINT UQ_ficha_hogar_001___);
DROP INDEX ficha_hogar.UQ_ficha_hogar_001___;
ALTER TABLE ficha_persona DROP (CONSTRAINT UQ_ficha_persona_001___);
DROP INDEX ficha_persona.UQ_ficha_persona_001___;
ALTER TABLE ficha_persona DROP (CONSTRAINT UQ_ficha_persona_002___);
DROP INDEX ficha_persona.UQ_ficha_persona_002___;
ALTER TABLE filtro_funcion DROP (CONSTRAINT UQ_filtro_funcion_001___);
DROP INDEX filtro_funcion.UQ_filtro_funcion_001___;
ALTER TABLE funcion DROP (CONSTRAINT UQ_funcion_001___);
DROP INDEX funcion.UQ_funcion_001___;
ALTER TABLE funcion_parametro DROP (CONSTRAINT UQ_funcion_parametro_001___);
DROP INDEX funcion_parametro.UQ_funcion_parametro_001___;
ALTER TABLE funcionario DROP (CONSTRAINT UQ_funcionario_001___);
DROP INDEX funcionario.UQ_funcionario_001___;
ALTER TABLE grupo_aplicacion DROP (CONSTRAINT UQ_grupo_aplicacion_001___);
DROP INDEX grupo_aplicacion.UQ_grupo_aplicacion_001___;
ALTER TABLE grupo_proceso DROP (CONSTRAINT UQ_grupo_proceso_001___);
DROP INDEX grupo_proceso.UQ_grupo_proceso_001___;
ALTER TABLE idioma_hogar DROP (CONSTRAINT UQ_idioma_hogar_001___);
DROP INDEX idioma_hogar.UQ_idioma_hogar_001___;
ALTER TABLE informe DROP (CONSTRAINT UQ_informe_001___);
DROP INDEX informe.UQ_informe_001___;
ALTER TABLE mensaje DROP (CONSTRAINT UQ_mensaje_001___);
DROP INDEX mensaje.UQ_mensaje_001___;
ALTER TABLE motivo_ina_esc DROP (CONSTRAINT UQ_motivo_ina_esc_001___);
DROP INDEX motivo_ina_esc.UQ_motivo_ina_esc_001___;
ALTER TABLE motivo_no_atencion DROP (CONSTRAINT UQ_motivo_no_atencion_001___);
DROP INDEX motivo_no_atencion.UQ_motivo_no_atencion_001___;
ALTER TABLE motivo_no_trabajo DROP (CONSTRAINT UQ_motivo_no_trabajo_001___);
DROP INDEX motivo_no_trabajo.UQ_motivo_no_trabajo_001___;
ALTER TABLE nivel_educativo DROP (CONSTRAINT UQ_nivel_educativo_001___);
DROP INDEX nivel_educativo.UQ_nivel_educativo_001___;
ALTER TABLE nivel_opcion_menu DROP (CONSTRAINT UQ_nivel_opcion_menu_001___);
DROP INDEX nivel_opcion_menu.UQ_nivel_opcion_menu_001___;
ALTER TABLE nivel_ubicacion DROP (CONSTRAINT UQ_nivel_ubicacion_001___);
DROP INDEX nivel_ubicacion.UQ_nivel_ubicacion_001___;
ALTER TABLE opcion_binaria DROP (CONSTRAINT UQ_opcion_binaria_001___);
DROP INDEX opcion_binaria.UQ_opcion_binaria_001___;
ALTER TABLE opcion_binaria DROP (CONSTRAINT UQ_opcion_binaria_002___);
DROP INDEX opcion_binaria.UQ_opcion_binaria_002___;
ALTER TABLE opcion_binaria DROP (CONSTRAINT UQ_opcion_binaria_003___);
DROP INDEX opcion_binaria.UQ_opcion_binaria_003___;
ALTER TABLE opcion_binaria DROP (CONSTRAINT UQ_opcion_binaria_004___);
DROP INDEX opcion_binaria.UQ_opcion_binaria_004___;
ALTER TABLE opcion_binaria DROP (CONSTRAINT UQ_opcion_binaria_005___);
DROP INDEX opcion_binaria.UQ_opcion_binaria_005___;
ALTER TABLE opcion_binaria DROP (CONSTRAINT UQ_opcion_binaria_006___);
DROP INDEX opcion_binaria.UQ_opcion_binaria_006___;
ALTER TABLE opcion_menu DROP (CONSTRAINT UQ_opcion_menu_001___);
DROP INDEX opcion_menu.UQ_opcion_menu_001___;
ALTER TABLE opcion_sistema DROP (CONSTRAINT UQ_opcion_sistema_001___);
DROP INDEX opcion_sistema.UQ_opcion_sistema_001___;
ALTER TABLE operador_com DROP (CONSTRAINT UQ_operador_com_001___);
DROP INDEX operador_com.UQ_operador_com_001___;
ALTER TABLE pagina DROP (CONSTRAINT UQ_pagina_001___);
DROP INDEX pagina.UQ_pagina_001___;
ALTER TABLE pagina_funcion DROP (CONSTRAINT UQ_pagina_funcion_001___);
DROP INDEX pagina_funcion.UQ_pagina_funcion_001___;
ALTER TABLE pagina_usuario DROP (CONSTRAINT UQ_pagina_usuario_001___);
DROP INDEX pagina_usuario.UQ_pagina_usuario_001___;
ALTER TABLE paquete DROP (CONSTRAINT UQ_paquete_001___);
DROP INDEX paquete.UQ_paquete_001___;
ALTER TABLE parametro DROP (CONSTRAINT UQ_parametro_001___);
DROP INDEX parametro.UQ_parametro_001___;
ALTER TABLE parametro_global DROP (CONSTRAINT UQ_parametro_global_001___);
DROP INDEX parametro_global.UQ_parametro_global_001___;
ALTER TABLE persona DROP (CONSTRAINT UQ_persona_001___);
DROP INDEX persona.UQ_persona_001___;
ALTER TABLE persona DROP (CONSTRAINT UQ_persona_002___);
DROP INDEX persona.UQ_persona_002___;
ALTER TABLE potencial_ben DROP (CONSTRAINT UQ_potencial_ben_001___);
DROP INDEX potencial_ben.UQ_potencial_ben_001___;
ALTER TABLE potencial_ben DROP (CONSTRAINT UQ_potencial_ben_002___);
DROP INDEX potencial_ben.UQ_potencial_ben_002___;
ALTER TABLE potencial_ben DROP (CONSTRAINT UQ_potencial_ben_003___);
DROP INDEX potencial_ben.UQ_potencial_ben_003___;
ALTER TABLE proceso DROP (CONSTRAINT UQ_proceso_001___);
DROP INDEX proceso.UQ_proceso_001___;
ALTER TABLE proveedor_dat_ext DROP (CONSTRAINT UQ_proveedor_dat_ext_001___);
DROP INDEX proveedor_dat_ext.UQ_proveedor_dat_ext_001___;
ALTER TABLE rol DROP (CONSTRAINT UQ_rol_001___);
DROP INDEX rol.UQ_rol_001___;
ALTER TABLE rol_aplicacion DROP (CONSTRAINT UQ_rol_aplicacion_001___);
DROP INDEX rol_aplicacion.UQ_rol_aplicacion_001___;
ALTER TABLE rol_filtro_funcion DROP (CONSTRAINT UQ_rol_filtro_funcion_001___);
DROP INDEX rol_filtro_funcion.UQ_rol_filtro_funcion_001___;
ALTER TABLE rol_funcion DROP (CONSTRAINT UQ_rol_funcion_001___);
DROP INDEX rol_funcion.UQ_rol_funcion_001___;
ALTER TABLE rol_pagina DROP (CONSTRAINT UQ_rol_pagina_001___);
DROP INDEX rol_pagina.UQ_rol_pagina_001___;
ALTER TABLE rol_usuario DROP (CONSTRAINT UQ_rol_usuario_001___);
DROP INDEX rol_usuario.UQ_rol_usuario_001___;
ALTER TABLE sexo_persona DROP (CONSTRAINT UQ_sexo_persona_001___);
DROP INDEX sexo_persona.UQ_sexo_persona_001___;
ALTER TABLE siono DROP (CONSTRAINT UQ_siono_001___);
DROP INDEX siono.UQ_siono_001___;
ALTER TABLE tipo_aba_agua DROP (CONSTRAINT UQ_tipo_aba_agua_001___);
DROP INDEX tipo_aba_agua.UQ_tipo_aba_agua_001___;
ALTER TABLE tipo_act_jupe DROP (CONSTRAINT UQ_tipo_act_jupe_001___);
DROP INDEX tipo_act_jupe.UQ_tipo_act_jupe_001___;
ALTER TABLE tipo_arc_dat_ext DROP (CONSTRAINT UQ_tipo_arc_dat_ext_001___);
DROP INDEX tipo_arc_dat_ext.UQ_tipo_arc_dat_ext_001___;
ALTER TABLE tipo_area DROP (CONSTRAINT UQ_tipo_area_001___);
DROP INDEX tipo_area.UQ_tipo_area_001___;
ALTER TABLE tipo_clase_recurso DROP (CONSTRAINT UQ_tipo_clase_recurso_001___);
DROP INDEX tipo_clase_recurso.UQ_tipo_clase_recurso_001___;
ALTER TABLE tipo_combustible DROP (CONSTRAINT UQ_tipo_combustible_001___);
DROP INDEX tipo_combustible.UQ_tipo_combustible_001___;
ALTER TABLE tipo_comparacion DROP (CONSTRAINT UQ_tipo_comparacion_001___);
DROP INDEX tipo_comparacion.UQ_tipo_comparacion_001___;
ALTER TABLE tipo_dato_par DROP (CONSTRAINT UQ_tipo_dato_par_001___);
DROP INDEX tipo_dato_par.UQ_tipo_dato_par_001___;
ALTER TABLE tipo_desecho_bas DROP (CONSTRAINT UQ_tipo_desecho_bas_001___);
DROP INDEX tipo_desecho_bas.UQ_tipo_desecho_bas_001___;
ALTER TABLE tipo_dominio DROP (CONSTRAINT UQ_tipo_dominio_001___);
DROP INDEX tipo_dominio.UQ_tipo_dominio_001___;
ALTER TABLE tipo_excepcion_ced DROP (CONSTRAINT UQ_tipo_excepcion_ced_001___);
DROP INDEX tipo_excepcion_ced.UQ_tipo_excepcion_ced_001___;
ALTER TABLE tipo_funcion DROP (CONSTRAINT UQ_tipo_funcion_001___);
DROP INDEX tipo_funcion.UQ_tipo_funcion_001___;
ALTER TABLE tipo_mat_paredes DROP (CONSTRAINT UQ_tipo_mat_paredes_001___);
DROP INDEX tipo_mat_paredes.UQ_tipo_mat_paredes_001___;
ALTER TABLE tipo_mat_piso DROP (CONSTRAINT UQ_tipo_mat_piso_001___);
DROP INDEX tipo_mat_piso.UQ_tipo_mat_piso_001___;
ALTER TABLE tipo_mat_techo DROP (CONSTRAINT UQ_tipo_mat_techo_001___);
DROP INDEX tipo_mat_techo.UQ_tipo_mat_techo_001___;
ALTER TABLE tipo_nodo DROP (CONSTRAINT UQ_tipo_nodo_001___);
DROP INDEX tipo_nodo.UQ_tipo_nodo_001___;
ALTER TABLE tipo_obj_ele_pen DROP (CONSTRAINT UQ_tipo_obj_ele_pen_001___);
DROP INDEX tipo_obj_ele_pen.UQ_tipo_obj_ele_pen_001___;
ALTER TABLE tipo_ocupacion_viv DROP (CONSTRAINT UQ_tipo_ocupacion_viv_001___);
DROP INDEX tipo_ocupacion_viv.UQ_tipo_ocupacion_viv_001___;
ALTER TABLE tipo_pagina DROP (CONSTRAINT UQ_tipo_pagina_001___);
DROP INDEX tipo_pagina.UQ_tipo_pagina_001___;
ALTER TABLE tipo_parametro DROP (CONSTRAINT UQ_tipo_parametro_001___);
DROP INDEX tipo_parametro.UQ_tipo_parametro_001___;
ALTER TABLE tipo_parametro_dom DROP (CONSTRAINT UQ_tipo_parametro_dom_001___);
DROP INDEX tipo_parametro_dom.UQ_tipo_parametro_dom_001___;
ALTER TABLE tipo_parametro_dom DROP (CONSTRAINT UQ_tipo_parametro_dom_002___);
DROP INDEX tipo_parametro_dom.UQ_tipo_parametro_dom_002___;
ALTER TABLE tipo_parametro_dom DROP (CONSTRAINT UQ_tipo_parametro_dom_003___);
DROP INDEX tipo_parametro_dom.UQ_tipo_parametro_dom_003___;
ALTER TABLE tipo_persona_hogar DROP (CONSTRAINT UQ_tipo_persona_hogar_001___);
DROP INDEX tipo_persona_hogar.UQ_tipo_persona_hogar_001___;
ALTER TABLE tipo_pieza_bano DROP (CONSTRAINT UQ_tipo_pieza_bano_001___);
DROP INDEX tipo_pieza_bano.UQ_tipo_pieza_bano_001___;
ALTER TABLE tipo_rastro_fun DROP (CONSTRAINT UQ_tipo_rastro_fun_001___);
DROP INDEX tipo_rastro_fun.UQ_tipo_rastro_fun_001___;
ALTER TABLE tipo_recurso DROP (CONSTRAINT UQ_tipo_recurso_001___);
DROP INDEX tipo_recurso.UQ_tipo_recurso_001___;
ALTER TABLE tipo_reg_pot_ben DROP (CONSTRAINT UQ_tipo_reg_pot_ben_001___);
DROP INDEX tipo_reg_pot_ben.UQ_tipo_reg_pot_ben_001___;
ALTER TABLE tipo_relacion_lab DROP (CONSTRAINT UQ_tipo_relacion_lab_001___);
DROP INDEX tipo_relacion_lab.UQ_tipo_relacion_lab_001___;
ALTER TABLE tipo_rol DROP (CONSTRAINT UQ_tipo_rol_001___);
DROP INDEX tipo_rol.UQ_tipo_rol_001___;
ALTER TABLE tipo_seguro_medico DROP (CONSTRAINT UQ_tipo_seguro_medico_001___);
DROP INDEX tipo_seguro_medico.UQ_tipo_seguro_medico_001___;
ALTER TABLE tipo_servicio_agua DROP (CONSTRAINT UQ_tipo_servicio_agua_001___);
DROP INDEX tipo_servicio_agua.UQ_tipo_servicio_agua_001___;
ALTER TABLE tipo_servicio_san DROP (CONSTRAINT UQ_tipo_servicio_san_001___);
DROP INDEX tipo_servicio_san.UQ_tipo_servicio_san_001___;
ALTER TABLE tipo_valor DROP (CONSTRAINT UQ_tipo_valor_001___);
DROP INDEX tipo_valor.UQ_tipo_valor_001___;
ALTER TABLE ubicacion DROP (CONSTRAINT UQ_ubicacion_001___);
DROP INDEX ubicacion.UQ_ubicacion_001___;
ALTER TABLE usuario DROP (CONSTRAINT UQ_usuario_001___);
DROP INDEX usuario.UQ_usuario_001___;
