--persona_acreditada_con_objeciones
create view auditoria_imp_ids (
                id_log_imp_ids,
                cedula,
                letra_cedula,
                apellidos,
                nombres,
                fecha_nacimiento,
                sexo,
                nacionalidad,
                estado_civil,
                lugar_nacimiento,
                es_indigena,
                importado,
                observacion,
                fecha_transaccion,
                nombre_archivo,
                codigo_archivo)
as select l.id_log_imp_ids,
          l.cedula,
          l.letra_cedula,
          l.apellidos,
          l.nombres,
          l.fecha_nacimiento,
          l.sexo,
          l.nacionalidad,
          l.estado_civil,
          l.lugar_nacimiento,
          l.es_indigena,
          l.importado,
          l.observacion,
          to_char(l.fecha_transaccion,'dd/mm/yyyy hh24:mm') as fecha_transaccion,
          l.nombre_archivo,
          l.codigo_archivo

from log_imp_ids l order by fecha_transaccion;