\echo
\echo DATABASE :pgdb :crvl
\echo
\echo
\echo dir :ddlxdir
\echo dir :joindir
\echo
\encoding
\encoding LATIN1
\encoding
\set AUTOCOMMIT off
\echo --------------------------------------------------------------------------
BEGIN TRANSACTION;
\echo --------------------------------------------------------------------------
\cd :ddlxdir
\i functions/setup.sql
\echo --------------------------------------------------------------------------
select * from setup_database_upgrade_count()
as (tipo varchar, cantidad integer)
order by 1;
\echo --------------------------------------------------------------------------
select  proname||'('||pg_catalog.oidvectortypes(proargtypes)||')' as firma_funcion
from    pg_proc inner join pg_namespace on pg_namespace.oid = pg_proc.pronamespace
where   proname like 'setup_database_upgrade_version%'
and     pg_catalog.oidvectortypes(proargtypes)=''
order   by proname;
\echo --------------------------------------------------------------------------
select setup_database_upgrade_drop();
\echo --------------------------------------------------------------------------
select setup_database_upgrade();
\echo --------------------------------------------------------------------------
\echo file:MHZDB201_100
\echo --------------------------------------------------------------------------
\cd :ddlxdir
\i base/MHZDB201_DEFAULTS_RENUMBERED.sql
\echo --------------------------------------------------------------------------
\echo file:MHZDB201_200
\echo --------------------------------------------------------------------------
\cd :joindir
\i MHZDB201_200_METADATA.sql
\echo --------------------------------------------------------------------------
\echo file:MHZDB201_300
\echo --------------------------------------------------------------------------
\cd :joindir
\i MHZDB201_300.sql
\echo --------------------------------------------------------------------------
\cd :joindir
\echo file:MHZDB201_400
\echo --------------------------------------------------------------------------
\i MHZDB201_400.sql
\echo --------------------------------------------------------------------------
\cd :joindir
\echo file:MHZDB201_500
\echo --------------------------------------------------------------------------
\i MHZDB201_500.sql
\echo --------------------------------------------------------------------------
\cd :joindir
\echo file:MHZDB201_600
\echo --------------------------------------------------------------------------
\i MHZDB201_600.sql
\echo --------------------------------------------------------------------------
select * from setup_database_upgrade_count()
as (tipo varchar, cantidad integer)
order by 1;
\echo --------------------------------------------------------------------------
COMMIT TRANSACTION;
\echo --------------------------------------------------------------------------
\q
