/**/
DROP VIEW IF EXISTS consulta_clase_recurso_1;
/**/
CREATE OR REPLACE VIEW consulta_clase_recurso_1 AS
SELECT
	clase_recurso.id_clase_recurso AS id_clase_recurso,
	clase_recurso.version_clase_recurso AS version_clase_recurso,
	clase_recurso.codigo_clase_recurso AS codigo_clase_recurso,
	clase_recurso.nombre_clase_recurso AS nombre_clase_recurso,
	clase_recurso.descripcion_clase_recurso AS descripcion_clase_recurso,
	clase_recurso.es_clase_recurso_independiente AS es_clase_recurso_independiente,
	clase_recurso.es_clase_recurso_sin_detalle AS es_clase_recurso_sin_detalle,
	clase_recurso.es_clase_recurso_con_arbol AS es_clase_recurso_con_arbol,
	clase_recurso.numero_tipo_clase_recurso AS numero_tipo_clase_recurso,
		tipo_clase_recurso_1x1.codigo_tipo_clase_recurso AS codigo_tipo_clase_recurs_1x1y2,
	clase_recurso.numero_tipo_recurso AS numero_tipo_recurso,
		tipo_recurso_1x2.codigo_tipo_recurso AS codigo_tipo_recurso_1x2y2,
	clase_recurso.id_funcion_seleccion AS id_funcion_seleccion,
		funcion_1x3.codigo_funcion AS codigo_funcion_1x3y3,
		funcion_1x3.nombre_funcion AS nombre_funcion_1x3y4,
		funcion_1x3.descripcion_funcion AS descripcion_funcion_1x3y5,
		funcion_1x3.numero_tipo_funcion AS numero_tipo_funcion_1x3y6,
		funcion_1x3.numero_tipo_rastro_fun AS numero_tipo_rastro_fun_1x3y7,
		funcion_1x3.id_dominio AS id_dominio_1x3y8,
		funcion_1x3.clausula_where AS clausula_where_1x3y9,
		funcion_1x3.clausula_order AS clausula_order_1x3y10,
		funcion_1x3.es_publica AS es_publica_1x3y11,
		funcion_1x3.es_programatica AS es_programatica_1x3y12,
		funcion_1x3.es_personalizada AS es_personalizada_1x3y13,
		funcion_1x3.es_segmentada AS es_segmentada_1x3y14,
		funcion_1x3.id_grupo_proceso AS id_grupo_proceso_1x3y15,
	clase_recurso.id_pagina_seleccion AS id_pagina_seleccion,
		pagina_1x4.codigo_pagina AS codigo_pagina_1x4y3,
		pagina_1x4.nombre_pagina AS nombre_pagina_1x4y4,
		pagina_1x4.descripcion_pagina AS descripcion_pagina_1x4y5,
		pagina_1x4.url_pagina AS url_pagina_1x4y6,
		pagina_1x4.id_aplicacion AS id_aplicacion_1x4y7,
		pagina_1x4.es_publica AS es_publica_1x4y8,
		pagina_1x4.numero_tipo_pagina AS numero_tipo_pagina_1x4y9,
		pagina_1x4.id_dominio AS id_dominio_1x4y10,
		pagina_1x4.id_dominio_maestro AS id_dominio_maestro_1x4y11,
		pagina_1x4.id_parametro AS id_parametro_1x4y12,
	clase_recurso.id_pagina_detalle AS id_pagina_detalle,
		pagina_1x5.codigo_pagina AS codigo_pagina_1x5y3,
		pagina_1x5.nombre_pagina AS nombre_pagina_1x5y4,
		pagina_1x5.descripcion_pagina AS descripcion_pagina_1x5y5,
		pagina_1x5.url_pagina AS url_pagina_1x5y6,
		pagina_1x5.id_aplicacion AS id_aplicacion_1x5y7,
		pagina_1x5.es_publica AS es_publica_1x5y8,
		pagina_1x5.numero_tipo_pagina AS numero_tipo_pagina_1x5y9,
		pagina_1x5.id_dominio AS id_dominio_1x5y10,
		pagina_1x5.id_dominio_maestro AS id_dominio_maestro_1x5y11,
		pagina_1x5.id_parametro AS id_parametro_1x5y12,
	clase_recurso.id_clase_recurso_maestro AS id_clase_recurso_maestro,
		clase_recurso_1x6.codigo_clase_recurso AS codigo_clase_recurso_1x6y3,
		clase_recurso_1x6.nombre_clase_recurso AS nombre_clase_recurso_1x6y4,
		clase_recurso_1x6.descripcion_clase_recurso AS descripcion_clase_recurs_1x6y5,
		clase_recurso_1x6.es_clase_recurso_independiente AS es_clase_recurso_indepen_1x6y6,
		clase_recurso_1x6.es_clase_recurso_sin_detalle AS es_clase_recurso_sin_det_1x6y7,
		clase_recurso_1x6.es_clase_recurso_con_arbol AS es_clase_recurso_con_arb_1x6y8,
		clase_recurso_1x6.numero_tipo_clase_recurso AS numero_tipo_clase_recurs_1x6y9,
		clase_recurso_1x6.numero_tipo_recurso AS numero_tipo_recurso_1x6y10,
		clase_recurso_1x6.id_funcion_seleccion AS id_funcion_seleccion_1x6y11,
		clase_recurso_1x6.id_pagina_seleccion AS id_pagina_seleccion_1x6y12,
		clase_recurso_1x6.id_pagina_detalle AS id_pagina_detalle_1x6y13,
		clase_recurso_1x6.id_clase_recurso_maestro AS id_clase_recurso_maestr_1x6y14,
		clase_recurso_1x6.id_clase_recurso_segmento AS id_clase_recurso_segmen_1x6y15,
		clase_recurso_1x6.id_clase_recurso_base AS id_clase_recurso_base_1x6y16,
		clase_recurso_1x6.id_grupo_aplicacion AS id_grupo_aplicacion_1x6y17,
		clase_recurso_1x6.id_aplicacion_web AS id_aplicacion_web_1x6y18,
		clase_recurso_1x6.limite_filas_consulta AS limite_filas_consulta_1x6y19,
		clase_recurso_1x6.limite_filas_informe AS limite_filas_informe_1x6y20,
		clase_recurso_1x6.orden_presentacion AS orden_presentacion_1x6y21,
		clase_recurso_1x6.es_clase_recurso_insertable AS es_clase_recurso_insert_1x6y22,
		clase_recurso_1x6.es_clase_recurso_modificable AS es_clase_recurso_modifi_1x6y23,
		clase_recurso_1x6.es_clase_recurso_eliminable AS es_clase_recurso_elimin_1x6y24,
		clase_recurso_1x6.es_clase_recurso_extendida AS es_clase_recurso_extend_1x6y25,
		clase_recurso_1x6.etiqueta_hipervinculo AS etiqueta_hipervinculo_1x6y26,
		clase_recurso_1x6.es_enumerador_con_numero AS es_enumerador_con_numer_1x6y27,
		clase_recurso_1x6.alias_clase_recurso AS alias_clase_recurso_1x6y28,
	clase_recurso.id_clase_recurso_segmento AS id_clase_recurso_segmento,
		clase_recurso_1x7.codigo_clase_recurso AS codigo_clase_recurso_1x7y3,
		clase_recurso_1x7.nombre_clase_recurso AS nombre_clase_recurso_1x7y4,
		clase_recurso_1x7.descripcion_clase_recurso AS descripcion_clase_recurs_1x7y5,
		clase_recurso_1x7.es_clase_recurso_independiente AS es_clase_recurso_indepen_1x7y6,
		clase_recurso_1x7.es_clase_recurso_sin_detalle AS es_clase_recurso_sin_det_1x7y7,
		clase_recurso_1x7.es_clase_recurso_con_arbol AS es_clase_recurso_con_arb_1x7y8,
		clase_recurso_1x7.numero_tipo_clase_recurso AS numero_tipo_clase_recurs_1x7y9,
		clase_recurso_1x7.numero_tipo_recurso AS numero_tipo_recurso_1x7y10,
		clase_recurso_1x7.id_funcion_seleccion AS id_funcion_seleccion_1x7y11,
		clase_recurso_1x7.id_pagina_seleccion AS id_pagina_seleccion_1x7y12,
		clase_recurso_1x7.id_pagina_detalle AS id_pagina_detalle_1x7y13,
		clase_recurso_1x7.id_clase_recurso_maestro AS id_clase_recurso_maestr_1x7y14,
		clase_recurso_1x7.id_clase_recurso_segmento AS id_clase_recurso_segmen_1x7y15,
		clase_recurso_1x7.id_clase_recurso_base AS id_clase_recurso_base_1x7y16,
		clase_recurso_1x7.id_grupo_aplicacion AS id_grupo_aplicacion_1x7y17,
		clase_recurso_1x7.id_aplicacion_web AS id_aplicacion_web_1x7y18,
		clase_recurso_1x7.limite_filas_consulta AS limite_filas_consulta_1x7y19,
		clase_recurso_1x7.limite_filas_informe AS limite_filas_informe_1x7y20,
		clase_recurso_1x7.orden_presentacion AS orden_presentacion_1x7y21,
		clase_recurso_1x7.es_clase_recurso_insertable AS es_clase_recurso_insert_1x7y22,
		clase_recurso_1x7.es_clase_recurso_modificable AS es_clase_recurso_modifi_1x7y23,
		clase_recurso_1x7.es_clase_recurso_eliminable AS es_clase_recurso_elimin_1x7y24,
		clase_recurso_1x7.es_clase_recurso_extendida AS es_clase_recurso_extend_1x7y25,
		clase_recurso_1x7.etiqueta_hipervinculo AS etiqueta_hipervinculo_1x7y26,
		clase_recurso_1x7.es_enumerador_con_numero AS es_enumerador_con_numer_1x7y27,
		clase_recurso_1x7.alias_clase_recurso AS alias_clase_recurso_1x7y28,
	clase_recurso.id_clase_recurso_base AS id_clase_recurso_base,
		clase_recurso_1x8.codigo_clase_recurso AS codigo_clase_recurso_1x8y3,
		clase_recurso_1x8.nombre_clase_recurso AS nombre_clase_recurso_1x8y4,
		clase_recurso_1x8.descripcion_clase_recurso AS descripcion_clase_recurs_1x8y5,
		clase_recurso_1x8.es_clase_recurso_independiente AS es_clase_recurso_indepen_1x8y6,
		clase_recurso_1x8.es_clase_recurso_sin_detalle AS es_clase_recurso_sin_det_1x8y7,
		clase_recurso_1x8.es_clase_recurso_con_arbol AS es_clase_recurso_con_arb_1x8y8,
		clase_recurso_1x8.numero_tipo_clase_recurso AS numero_tipo_clase_recurs_1x8y9,
		clase_recurso_1x8.numero_tipo_recurso AS numero_tipo_recurso_1x8y10,
		clase_recurso_1x8.id_funcion_seleccion AS id_funcion_seleccion_1x8y11,
		clase_recurso_1x8.id_pagina_seleccion AS id_pagina_seleccion_1x8y12,
		clase_recurso_1x8.id_pagina_detalle AS id_pagina_detalle_1x8y13,
		clase_recurso_1x8.id_clase_recurso_maestro AS id_clase_recurso_maestr_1x8y14,
		clase_recurso_1x8.id_clase_recurso_segmento AS id_clase_recurso_segmen_1x8y15,
		clase_recurso_1x8.id_clase_recurso_base AS id_clase_recurso_base_1x8y16,
		clase_recurso_1x8.id_grupo_aplicacion AS id_grupo_aplicacion_1x8y17,
		clase_recurso_1x8.id_aplicacion_web AS id_aplicacion_web_1x8y18,
		clase_recurso_1x8.limite_filas_consulta AS limite_filas_consulta_1x8y19,
		clase_recurso_1x8.limite_filas_informe AS limite_filas_informe_1x8y20,
		clase_recurso_1x8.orden_presentacion AS orden_presentacion_1x8y21,
		clase_recurso_1x8.es_clase_recurso_insertable AS es_clase_recurso_insert_1x8y22,
		clase_recurso_1x8.es_clase_recurso_modificable AS es_clase_recurso_modifi_1x8y23,
		clase_recurso_1x8.es_clase_recurso_eliminable AS es_clase_recurso_elimin_1x8y24,
		clase_recurso_1x8.es_clase_recurso_extendida AS es_clase_recurso_extend_1x8y25,
		clase_recurso_1x8.etiqueta_hipervinculo AS etiqueta_hipervinculo_1x8y26,
		clase_recurso_1x8.es_enumerador_con_numero AS es_enumerador_con_numer_1x8y27,
		clase_recurso_1x8.alias_clase_recurso AS alias_clase_recurso_1x8y28,
	clase_recurso.id_grupo_aplicacion AS id_grupo_aplicacion,
		grupo_aplicacion_1x9.codigo_grupo_aplicacion AS codigo_grupo_aplicacion_1x9y3,
		grupo_aplicacion_1x9.nombre_grupo_aplicacion AS nombre_grupo_aplicacion_1x9y4,
		grupo_aplicacion_1x9.descripcion_grupo_aplicacion AS descripcion_grupo_aplica_1x9y5,
	clase_recurso.id_aplicacion_web AS id_aplicacion_web,
	clase_recurso.limite_filas_consulta AS limite_filas_consulta,
	clase_recurso.limite_filas_informe AS limite_filas_informe,
	clase_recurso.orden_presentacion AS orden_presentacion,
	clase_recurso.es_clase_recurso_insertable AS es_clase_recurso_insertable,
	clase_recurso.es_clase_recurso_modificable AS es_clase_recurso_modificable,
	clase_recurso.es_clase_recurso_eliminable AS es_clase_recurso_eliminable,
	clase_recurso.es_clase_recurso_extendida AS es_clase_recurso_extendida,
	clase_recurso.etiqueta_hipervinculo AS etiqueta_hipervinculo,
	clase_recurso.es_enumerador_con_numero AS es_enumerador_con_numero,
	clase_recurso.alias_clase_recurso AS alias_clase_recurso
FROM
	clase_recurso clase_recurso
	INNER JOIN tipo_clase_recurso tipo_clase_recurso_1x1 ON tipo_clase_recurso_1x1.numero_tipo_clase_recurso = clase_recurso.numero_tipo_clase_recurso
	INNER JOIN tipo_recurso tipo_recurso_1x2 ON tipo_recurso_1x2.numero_tipo_recurso = clase_recurso.numero_tipo_recurso
	LEFT OUTER JOIN funcion funcion_1x3 ON funcion_1x3.id_funcion = clase_recurso.id_funcion_seleccion
	LEFT OUTER JOIN pagina pagina_1x4 ON pagina_1x4.id_pagina = clase_recurso.id_pagina_seleccion
	LEFT OUTER JOIN pagina pagina_1x5 ON pagina_1x5.id_pagina = clase_recurso.id_pagina_detalle
	LEFT OUTER JOIN clase_recurso clase_recurso_1x6 ON clase_recurso_1x6.id_clase_recurso = clase_recurso.id_clase_recurso_maestro
	LEFT OUTER JOIN clase_recurso clase_recurso_1x7 ON clase_recurso_1x7.id_clase_recurso = clase_recurso.id_clase_recurso_segmento
	LEFT OUTER JOIN clase_recurso clase_recurso_1x8 ON clase_recurso_1x8.id_clase_recurso = clase_recurso.id_clase_recurso_base
	LEFT OUTER JOIN grupo_aplicacion grupo_aplicacion_1x9 ON grupo_aplicacion_1x9.id_grupo_aplicacion = clase_recurso.id_grupo_aplicacion;

